minor update of README.md
solid/process pull request #240
Opened 2020-11-09 21:47 UTC by TallTed

minor fix to markup, plus language clarification

2020-12-16 19:43 UTC, TallTed commented
Someone else also fixed the markup, and that's been merged.

My language fix, changing the non-English "with the aim is to develop" to the English "with the aim of developing" remains.

(@justinwb @timbl -- I can't add reviewers per se, so I'm pinging you this way.)

2022-12-27 18:52 UTC, TallTed commented
@csarven @timbl — Maybe this could be merged soon, so another two years of languishing don't require another round of conflict repair?  (Might be that someone(s) should also be listed as CODEOWNERS for this repo?)

2023-01-25 04:12 UTC, TallTed commented
or @timea-solid?

Maybe the **Test Suite** section was meant to be deleted, as it's the only diff remaining between my branch and the original.

2023-01-25 08:26 UTC, timea-solid commented
@TallTed yes I suspect the same. However, I need to check at the next meeting.

2023-01-25 12:55 UTC, csarven requested changes

2023-01-25 12:55 UTC, csarven commented on README.md
> +Test Suite Developers work with the aim of developing a [test suite](https://github.com/solid/test-suite) that can be used to verify an implementation against the Solid specification.
```suggestion
# Solid QA

Solid QA policy, processes, and procedures are developed through the [Test Suite Panel](https://github.com/solid/test-suite-panel/) as per the [Test Suite Panel Charter](https://github.com/solid/process/blob/main/test-suite-panel-charter.md) with the aim to give authors of technical reports and software implementers confidence that they can rely on the Solid ecosystem to deliver on the promise of interoperability based on open standards.
```

2023-01-25 18:25 UTC, TallTed commented on README.md
> +Test Suite Developers work with the aim of developing a [test suite](https://github.com/solid/test-suite) that can be used to verify an implementation against the Solid specification.
@csarven — I think this might warrant its own PR, as it's not tied to any change being made by mine.

In either case, I'd suggest changing `authors of technical reports and software implementers` to `authors of technical reports and implementers of software`.

2023-01-25 19:21 UTC, csarven commented on README.md
> +Test Suite Developers work with the aim of developing a [test suite](https://github.com/solid/test-suite) that can be used to verify an implementation against the Solid specification.
I believe the essence of what needs to be added is better captured by my suggestion in that it represents current state of affairs - there is a whole set of work there, where solid/test-suite is acknowledged one of the work items.

I've updated the change request with your suggestion, thanks.

2023-02-08 16:07 UTC, jaxoncreed approved these changes
LGTM

2023-02-11 14:49 UTC, timea-solid approved these changes

2023-02-11 14:50 UTC, timea-solid commented
@csarven are oyu ok to approve it now?

2023-02-11 14:55 UTC, csarven commented on README.md
> +Solid QA policy, processes, and procedures are developed through the [Test Suite Panel](https://github.com/solid/test-suite-panel/) as per the [Test Suite Panel Charter](https://github.com/solid/proc
```suggestion
[Solid QA](https://solidproject.org/ED/qa) policy, processes, and procedures are developed through the [Test Suite Panel](https://github.com/solid/test-suite-panel/) as per the [Test Suite Panel Charter](https://github.com/solid/process/blob/main/test-suite-panel-charter.md) with the aim to give authors of technical reports and implementers of software confidence that they can rely on the Solid ecosystem to deliver on the promise of interoperability based on open standards.
```

2023-02-11 14:55 UTC, csarven approved these changes

2023-02-11 14:57 UTC, merged