Creating the DEI Team
solid/process pull request #254
Opened 2021-04-13 22:38 UTC by MarrelleBailey

Please leave feedback and the next steps to make this happen officially. I hope this helps us to bring in more diversity into the Solid community!

2021-04-14 06:02 UTC, csarven requested changes

2021-04-14 06:02 UTC, csarven commented on DEI Team
> +* Administrator: Sarven Capadisli
```suggestion
* Administrator: [Sarven Capadisli](https://csarven.ca/#i) ([Inrupt](https://inrupt.com/))
```

2021-04-14 11:19 UTC, RubenVerborgh reviewed
Great to see these plans unfold. Happy to help spread the message.

2021-04-14 11:19 UTC, RubenVerborgh commented on DEI Team
> +This charter sets out to explain the Diversity, Equity, and Inclusion Team (DEIT). It provides a concise overview of increasing ethnic & gender diversity, representation, and equity aligning with the
Are there more forms of diversity in addition to ethnicity and gender?
Thinking about ability, language, for instance.

Perhaps we can rephrase to something like "diversity (such as X, Y, Z)" so we don't have to be exhaustive.

2021-04-14 11:19 UTC, RubenVerborgh commented on DEI Team
> +This charter sets out to explain the Diversity, Equity, and Inclusion Team (DEIT). It provides a concise overview of increasing ethnic & gender diversity, representation, and equity aligning with the
```suggestion
This charter sets out to explain the Diversity, Equity, and Inclusion Team (DEIT). It provides a concise overview of increasing ethnic & gender diversity, representation, and equity aligning with the community’s long-term goals. The Team shall review interactions, make sure there are opportunities for those in underrepresented groups, and make recommendations to the Solid Team and Community.
```

(for consistency)

2021-04-14 11:19 UTC, RubenVerborgh commented on DEI Team
> +The Director of Solid and administrators will determine the number of team members, always greater than two, and meet or exceed regulatory requirements. All those in an administrator role must disclo
I don't understand the phrasing

```
and meet or exceed regulatory requirements
```

2021-04-14 11:19 UTC, RubenVerborgh commented on DEI Team
> +* Increasing diversity, inclusion, and equity throughout the Solid community/ecosystem
The bullet points do not seem connected to the previous paragraph.

It reads: "Authority – none expressed – here's a list". Are these a list of goals?

2021-04-14 14:59 UTC, MarrelleBailey reviewed
Made changes based on additional comments

2021-04-14 14:59 UTC, MarrelleBailey commented on DEI Team
> +* Increasing diversity, inclusion, and equity throughout the Solid community/ecosystem
Yes, they are a list of goals. Let me reword that section.

2021-04-14 22:06 UTC, jeff-zucker commented on DEI Team
> +This charter sets out to explain the Diversity, Equity, and Inclusion Team (DEIT). It provides a concise overview of increasing ethnic & gender diversity, representation, and equity aligning with the
We had wanted to avoid naming all the possible under-represented groups because we would certainly leave someone out.  Perhaps it should be phrased "increasing ethnic, gender, and other forms of diversity .,."

2021-04-15 04:18 UTC, MarrelleBailey commented on DEI Team
> +This charter sets out to explain the Diversity, Equity, and Inclusion Team (DEIT). It provides a concise overview of increasing ethnic & gender diversity, representation, and equity aligning with the
Yes, @jeff-zucker, I agree maybe that's the better phrasing. As you said, the last thing we want to do is exclude anyone.

2021-04-15 04:19 UTC, MarrelleBailey commented on DEI Team
> +The Director of Solid and administrators will determine the number of team members, always greater than two, and meet or exceed regulatory requirements. All those in an administrator role must disclo
It means it doesn't go over a specific amount than what the Team and the Director of Solid agree on. We can change this wording when we think of a member limit. Still figuring some of these parts out.

2021-04-15 08:27 UTC, RubenVerborgh commented on DEI Team
> +This charter sets out to explain the Diversity, Equity, and Inclusion Team (DEIT). It provides a concise overview of increasing ethnic & gender diversity, representation, and equity aligning with the
Note that there is also a listing lower in the document: https://github.com/solid/process/pull/254/files#diff-f7e887d6a2e1de53e000676febfc325409c6b55b67577539bbbad5af50e08443R16 (which explicitly says it is not limiting).

Maybe it can be removed here then?

2021-04-15 15:17 UTC, MarrelleBailey commented on DEI Team
> +This charter sets out to explain the Diversity, Equity, and Inclusion Team (DEIT). It provides a concise overview of increasing ethnic & gender diversity, representation, and equity aligning with the
Actually, that should work. We can remove it for now! And thank you for the link.

2021-04-15 15:19 UTC, MarrelleBailey commented on DEI Team
> +This charter sets out to explain the Diversity, Equity, and Inclusion Team (DEIT). It provides a concise overview of increasing ethnic & gender diversity, representation, and equity aligning with the
@jeff-zucker What are your thoughts? Let's change the phrasing you suggested and add it lower in the doc to remain consistent.

2021-04-15 15:37 UTC, jeff-zucker commented on DEI Team
> +This charter sets out to explain the Diversity, Equity, and Inclusion Team (DEIT). It provides a concise overview of increasing ethnic & gender diversity, representation, and equity aligning with the
That sounds like a good plan.

2021-04-21 11:33 UTC, justinwb commented
I believe the intent is for this file to be recognized at Markdown - recommend changing filename to dei.md so github recognizes it as such.

2021-04-21 11:39 UTC, justinwb commented on DEI Team
> +The Team shall consist of both administrators and community members (CM). All administrators and CM join on a volunteer basis. The administrators will serve a term of one year and are appointed by th
I worry about creating confusing reusing the role  name of administrator here when we already have that role elsewhere.

2021-04-21 11:39 UTC, justinwb commented on DEI Team
> +The DEI Team administrators will report their activities to the Director of Solid, in summary, published quarterly.
Are these reports reports shared only with the director, or published quarterly for public consumption as well?

2021-04-21 11:39 UTC, justinwb commented on DEI Team
> +This charter was written by Marrelle Bailey and approved by the Solid Team on February 25, 2021. And was last updated on April 13, 2021.
Would the approval date on the charter = the eventual merge date of this PR? It may be that there are two dates, one date on 2/25 when the team voted in support of the initiative, and then the date that this charter document finished review and was merged?

2021-04-21 14:50 UTC, MarrelleBailey commented on DEI Team
> +The Team shall consist of both administrators and community members (CM). All administrators and CM join on a volunteer basis. The administrators will serve a term of one year and are appointed by th
I agree with changing it to dei.md, and I feel a little stumped on the role title. There's been a lot of back and forth. Do you have any ideas?

2021-04-21 14:51 UTC, MarrelleBailey commented on DEI Team
> +The DEI Team administrators will report their activities to the Director of Solid, in summary, published quarterly.
Actually we should do both thank you for pointing that out!

2021-04-29 23:37 UTC, kjetilk approved these changes
I think it looks very good now.

2021-04-30 20:28 UTC, justinwb approved these changes
Changes look good to me @MarrelleBailey  ✅

2021-05-03 19:03 UTC, TallTed requested changes
Fixed some typos, punctuation, and language. No meaning should be changed by these tweaks.

2021-05-03 19:03 UTC, TallTed commented on DEI Team
> +This charter was written by Marrelle Bailey and approved by the Solid Team on February 25, 2021. And was last updated on April 28, 2021.
```suggestion
The DEIT will meet at least quarterly and more often as needed. A majority of the community members shall constitute a quorum. The lead chair will keep a copy of the DEIT meeting minutes and forward a copy to the board secretary. The chair members may invite any director, officer, staff member, expert, or other advisor who isn’t a committee member to sit in, listen, and advise; however, these individuals will have no voting power.
The DEIT team will review its charter twice a year and recommend any proposed changes to the board for review. This document will also be available to the public. If you would like to make changes, please submit a PR.
This charter was written by Marrelle Bailey, approved by the Solid Team on February 25, 2021, and last updated on April 28, 2021.
```

2021-05-04 06:38 UTC, csarven requested changes
re https://github.com/solid/process/pull/254#discussion_r612956034 , it was marked as resolved without changes but no reason was given.

>All those in an administrator role must disclose outside ties to organizations/companies/directorships.

is sufficient. The following sentence is unnecessary:

>Ties that should be disclosed are working with organizations or companies affiliated with Solid like Janeiro Digital, Inrupt, etc.

The charter should not mention companies in this way.

2021-05-04 06:38 UTC, csarven commented on DEI Team
> +This charter was written by Marrelle Bailey and approved by the Solid Team on February 25, 2021. And was last updated on April 28, 2021.
Wouldn't "DEIT" do instead of "DEIT team"?

2021-05-04 14:26 UTC, oliviamrl commented on DEI Team
> +The DEIT has no expressed or implied power or authority above any other Teams in Solid. The DEIT will hold other Soid Teams accountable in all significant decisions and changes the DEIT makes for the
typo - The DEIT will hold other **Soid Teams accountable

2021-05-04 14:29 UTC, csarven approved these changes

2021-05-04 17:39 UTC, TallTed approved these changes

2021-05-07 16:21 UTC, timbl approved these changes
A good idea.

2021-05-11 15:04 UTC, merged