Solid Editors’ Technical Report Development Process
solid/process pull request #257
Opened 2021-06-15 15:03 UTC by kjetilk

The Solid Editors Group has prepared a process designed to focus the specification development process. In this process, the Solid Editors will convene weekly and maintain a monthly cycle to triage, prioritize and select issues for work in the following time period. We hope that this will help the community converge on consensus faster and thus speed up the development of the Solid specifications.

2021-06-16 15:54 UTC, TallTed requested changes

2021-06-16 15:54 UTC, TallTed commented on README.md
> +The [Solid Editors](https://github.com/orgs/solid/teams/editors) [maintain a monthly development cycle](solid-editors-tr-process.md) where it selects issues amongst the open issues for consideration
```suggestion
The [Solid Editors](https://github.com/orgs/solid/teams/editors) [maintain a monthly development cycle](solid-editors-tr-process.md) in which they select issues from the open issues for consideration in the next time period to help focus the community towards efficiently resolving outstanding issues. It is hoped that community members will participate in the process, guided by the Solid Editors and within the time frames they set.
```

2021-06-16 15:54 UTC, TallTed commented on solid-editors-tr-process.md
> +sufficiently clear to enter the drafting phase, in which a formal text
```suggestion
different purpose and dynamic. Sometimes, the consensus is already
sufficiently clear to enter the drafting phase, in which case a formal text
```

2021-06-16 15:54 UTC, TallTed commented on solid-editors-tr-process.md
> +a consensus-building phase is required. It is not necessarily a good
```suggestion
is drafted. In most cases, consensus has not yet been reached, so
a consensus-building phase is required. It is not generally a good
```

2021-06-16 15:54 UTC, TallTed commented on solid-editors-tr-process.md
> +before or within the consensus phase. Sometimes, the issue is unclear
```suggestion
progress. Identifying the need for a UCR phase can be happe
before or during the consensus phase. Sometimes, the issue is unclear
```

2021-06-16 15:54 UTC, TallTed commented on solid-editors-tr-process.md
> +to the long-term scalability of the proposal, in which case an
```suggestion
because there is insufficient implementation experience or doubt of
the long-term scalability of the proposal, in which case an
```

2021-06-16 15:54 UTC, TallTed commented on solid-editors-tr-process.md
> +time frame.
```suggestion
This process does not replace the process for submitting and deciding
upon issues; it mainly guides how and when Solid Editors will engage
on certain issues and/or rally support for resolution within a given
time frame.
```

2021-06-16 15:54 UTC, TallTed commented on solid-editors-tr-process.md
> +describes this in more detail:
```suggestion
The phases described below are sorted by shortest path to completion.
Mature issues may be ready to enter the drafting phase immediately,
with a quick route to being finished. In other cases, an issue may
arise during the consensus phase, or earlier, in the UCR phase. Thus,
this process differs from a conventional software development process
that usually starts with a UCR phase. The following figure describes
this in more detail:
```

2021-06-16 15:54 UTC, TallTed commented on solid-editors-tr-process.md
> +but for now the Editors scope will be limited to issues in the
```suggestion
For an issue to be considered by the Editors, it must have been
submitted [according to the process](https://github.com/solid/process#drafting-proposals).
For now, the Editors' scope will be limited to issues in the
```

2021-06-16 15:54 UTC, TallTed commented on solid-editors-tr-process.md
> +feature set, and so, Editors may decide to group them.
```suggestion
Individual issues are often part of a larger problem space or feature
set; in such case, the Editors may decide to group them.
```

2021-06-16 15:54 UTC, TallTed commented on solid-editors-tr-process.md
> +An issue can enter drafting phase if any of the following are met:
```suggestion
An issue can enter the drafting phase if either of the following is met:
```

2021-06-16 15:54 UTC, TallTed commented on solid-editors-tr-process.md
> +  that drafting can begin.
```suggestion
  for drafting to begin.
```

2021-06-16 15:54 UTC, TallTed commented on solid-editors-tr-process.md
> +  [Actions if rough consensus cannot be reached](#actions-if-rough-consensus-cannot-be-reached)
```suggestion
  [Actions if rough consensus cannot be reached](#actions-if-rough-consensus-cannot-be-reached).
```

2021-06-16 18:02 UTC, TallTed requested changes

2021-06-16 18:02 UTC, TallTed commented on solid-editors-tr-process.md
> +audience that does not follow the work closely.
```suggestion
A summary of the selected issues will be written, targeting a 
technical audience that does not follow the work closely.
```

2021-06-16 21:10 UTC, kjetilk commented
Thanks a lot @TallTed , great to have your feedback to improve my language!

2021-06-17 20:12 UTC, TallTed commented on solid-editors-tr-process.md
> +progress. Identifying the need for a UCR phase can be happe
```suggestion
progress. Identifying the need for a UCR phase can happen

```

2021-06-17 20:17 UTC, TallTed commented on solid-editors-tr-process.md
> +  for drafting to begin.
```suggestion
* A Solid Editor has deemed that the prior experience on the issue,
  particularly by existing implementations, is sufficient for drafting
  to begin.
```

2021-06-23 22:17 UTC, TallTed commented on solid-editors-tr-process.md
> +Editors will review any open Pull Requests. If it finds that a
```suggestion
Editors will review any open Pull Requests. If they find that a 

```

2021-06-24 19:27 UTC, TallTed commented on solid-editors-tr-process.md
> +
```suggestion
```
Github has started adding blank lines to suggested changes.  Suggester has to remember to delete the extra newline, else it results in this.... which I'm suggesting be deleted now.  *sigh*

2021-06-24 20:39 UTC, kjetilk commented on solid-editors-tr-process.md
> +
Yeah, pretty weird...

2021-06-29 12:49 UTC, timbl approved these changes
LGTM

2021-06-29 12:49 UTC, merged