Update process.
solid/process pull request #270
Opened 2022-03-04 16:52 UTC by barath

Update process to improve clarity, increase accountability, streamline progress of specification features, and enhance collaboration in the Solid ecosystem.

2022-03-07 08:11 UTC, RubenVerborgh reviewed
Is there an issue, document, or other text that was a trigger for these changes?
I feel like I am missing context (but there might be none).

2022-03-07 08:11 UTC, RubenVerborgh commented on README.md
> +The following describes how changes to the specifications in the Solid ecosystem may be proposed and accepted. Anyone may submit a proposal to alter this process; such proposals will be reviewed only
Is there a document or pointer for these changes?

The "will be reviewed only" is a bit strong, and unenforceable; I expect there will be reviews by multiple people. Do we mean that Tim is the only approver?

Language-wise, I would just use "[a/the] Solid Director" to avoid redundancy.

2022-03-07 10:10 UTC, kjetilk requested changes
Thank you very much for your contribution @barath . 

I don't think I would be opposed to most of these changes, but it is also not clear to me what problems these changes seek to address and how they make a contribution to addressing them. I agree with @RubenVerborgh , this lacks context.

I find that the Atlassian blog has a good post titled ["The (written) unwritten guide to pull requests"](https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests), because these guidelines are generally unwritten, but I believe code and prose should generally be kept to the same standard when it comes to PRs, atomic commits, small PRs: "one concern, one PR", what and why it changed well described.

This PRs contains multiple concerns. One concern seems to be wordsmithing, some of it is moving paragraphs around. It is probably a low threshold to merge, those should be in its own PR. 

Then, it removes certain things, like the documents that informed this. I don't have strong opinions on this, but that's a very different thing than introducing the role of a Release Manager, for example. They should not be in the same PR.

Then, there are things that seem to belong in a different document as it pertains more to how Solid Editors operate.

As a first step, I suggest breaking this up in several PRs where the what and why is stated in the PR description.

2022-03-09 11:59 UTC, justinwb commented on README.md
> +The following describes how changes to the specifications in the Solid ecosystem may be proposed and accepted. Anyone may submit a proposal to alter this process; such proposals will be reviewed only
> The "will be reviewed only" is a bit strong, and unenforceable; I expect there will be reviews by multiple people. Do we mean that Tim is the only approver?

Agree with @RubenVerborgh here - maybe something like the following would work better?

```suggestion
The following describes how changes to the specifications in the Solid ecosystem may be proposed and accepted. Anyone may submit a proposal to alter this process; such proposals may be reviewed by members of the Solid team, and must be approved by the [Solid Director](https://github.com/timbl).
```

2022-03-09 11:59 UTC, justinwb commented on README.md
> +Any individual who has been involved in proposals to improve the [Solid Specification](https://github.com/solid/specification) has provided a valuable service to the [Solid Project](https://www.solid
Yes that was exactly the rationale at the time. I think it (and similar statements in that vein) can be safely removed now for the sake of making the document as concise as possible.

2022-03-09 11:59 UTC, justinwb commented on README.md
> +Solid Panels are groups of contributors focused on a specific problem or domain relevant to Solid, with an aim to propose changes to the [Solid Specification](https://github.com/solid/specification).
I think we're missing a pathway for how and where the agreement to that W3C CLA takes place. For example, in [Solid Specification](https://github.com/solid/specification/) there isn't a CONTRIBUTING document that implies the work is being done under the W3C CLA, nor language to that effect in the main README, which seems to be the common approach in other W3C endeavors. The [Shape Trees Specification](https://github.com/shapetrees/specification/) is an example where we aimed to mirror the pattern common in other W3C specification repos - with a [CONTRIBUTING](https://github.com/shapetrees/specification/blob/main/CONTRIBUTING.md) document and pointer from the main README. We may want to do something similar in the main specification repo and the panels.

2022-03-09 11:59 UTC, justinwb commented on README.md
> +If a contributor disapproves of Candidate Proposal that is under consideration, they must provide substantive, written comments that contain proposed remedies to the Solid Editors at least 1 week bef
```suggestion
If a contributor disapproves of a Candidate Proposal that is under consideration, they must provide substantive, written comments that contain proposed remedies to the Solid Editors at least 1 week before the end of the review time window. The Solid Editors will consider the comments and suggest possible remedies.
```

2022-03-09 13:58 UTC, csarven reviewed
In addition to echoing Ruben and Kjetil's reviews, I'll be brief about another fundamental issue with this PR:

>Update process to improve clarity, increase accountability, streamline progress of specification features, and enhance collaboration in the Solid ecosystem.

>Context: We've conducted an analysis of the existing spec process and found that there are gaps and exists potential for deadlock. This PR is designed to help address those gaps and optimize the flow through the process.

In order to help readers/reviewers, can this be expressed without weasel wording? It'd also help to support the claims with data/analysis/citations because the proposed text neither appears to make a clear connection or describes how exactly it addresses what's intended.

2022-03-15 14:39 UTC, timbl commented
@kjetilk Thank you for your review.  It is currently the only blocking one.  I think we have addressed many of the things you mention.  We have decided not to ask Barath to resubmit it as a bunch of small ones.  Could you change the state of your review to approve?

2022-03-15 18:49 UTC, csarven commented
@timbl , there is feedback from the reviewers that can still be incorporated. Engaging in the comments will also help the PR move forward in a timely manner.

This is all irrespective of the PR being more atomic about its intention - for a number of reasons - which was discussed and agreed as per the 2022-03-09 Editors Team meeting: https://github.com/solid/specification/blob/main/meetings/2022-03-09.md .

Having said that, if this PR goes through as is, I'd view this as an exception made with your Director hat on. I do not think that it should set the precedent for future PRs and its review process to be along the lines we've seen here, especially when it noticeably differs from community's current (best) practice/culture.

My two centime/rappen/centesimo/rap.

2022-03-15 23:03 UTC, RubenVerborgh commented
I unfortunately see that most of my comments have not been addressed; however I do not consider them blocking.

I think we all want the process to move fast, but we should be careful not to inadvertently slow things down by trying to rush.

Concretely, for a next opportunity, let's first create issues (so we understand what's broken), and then fix them one by one (so we can compare if it fixes what was broken).

2022-03-16 17:46 UTC, merged