Add draft W3C Working Group charter for Solid
solid/process pull request #315
Opened 2022-11-30 16:55 UTC by barath

As requested in Issue #311, this PR adds a draft W3C Working Group charter for Solid.

2022-12-06 11:28 UTC, tomhgmns commented
Thank you for the proposal. Looks great!

Could there also be a chairperson who represents Digita/use.id?

2022-12-06 11:58 UTC, woutermont commented on draft-working-group-charter/index.html
> +                    Recommend a set of protocol behaviors and best practices for the use in Solid of the OpenID Connect (OIDC) identity layer on top of the OAuth 2.0 protocol.
Also, i.m.o. this seems to fall under the previous point, since OIDC is an example of one of the existing authentication standards.

2022-12-06 11:58 UTC, woutermont commented on draft-working-group-charter/index.html
> +                        Definition of authentication or authorization protocols
In the assumption that we plan to take Solid-OIDC (an authentication protocol) in the Working Group, this is an incorrect statement.

2022-12-06 11:58 UTC, woutermont commented on draft-working-group-charter/index.html
> +                    In order to advance to
```suggestion
                    In order to advance to a
```

2022-12-06 11:58 UTC, woutermont commented on draft-working-group-charter/index.html
> +                        The group will maintain and advance a <a href="">test suite (LINK TBD)</a> enabling interoperability testing.
> [...] a test suite enabling **interoperability** testing

Interoperability testing specifically, or testing in general (including interoperability testing)?

2022-12-06 11:58 UTC, woutermont commented on draft-working-group-charter/index.html
> +                    The Solid Working Group will deliver the following W3C normative specifications:
```suggestion
                    The Solid Working Group will deliver the following W3C normative specifications.
```

2022-12-06 11:58 UTC, woutermont commented on draft-working-group-charter/index.html
> +security with the relevant Working and Interest Groups, and with the <a href="https://www.w3.org/2001/tag/" title="Technical Architecture Group">TAG</a>. Invitation for review must be issued during e
```suggestion
security with the relevant Working and Interest Groups, and with the <a href="https://www.w3.org/2001/tag/" title="Technical Architecture Group">TAG</a>. Invitation for review must be issued during each major standards-track document transition, including the <a href="https://www.w3.org/Consortium/Process/#RecsWD" title="First Public Working Draft">FPWD</a> and at least 3 months before the <a href="https://www.w3.org/Consortium/Process/#RecsCR" title="Candidate Recommendation">CR</a>, and should be issued when major changes occur in a specification.
```

2022-12-06 11:58 UTC, woutermont commented on draft-working-group-charter/index.html
> +                Additional technical coordination with the following Groups will be made, per the <a href="https://www.w3.org/Consortium/Process/#WGCharter">W3C Process Document</a>:
```suggestion
                Additional technical coordination with the following Groups will be made, per the <a href="https://www.w3.org/Consortium/Process/#WGCharter">W3C Process Document</a>.
```

2022-12-06 12:01 UTC, woutermont commented
☝️ Some minor questions and suggestions. Great draft!

2022-12-06 15:19 UTC, TallTed commented on draft-working-group-charter/index.html
> +                    The Solid Working Group will deliver the following W3C normative specifications:
The colon (":") is appropriately used here.  I recommend against this change.

2022-12-06 15:26 UTC, TallTed commented on draft-working-group-charter/index.html
> +            The <strong>mission</strong> of the <a href="">Solid Working Group (LINK TBD)</a> is to standardize the Solid Protocol and its use of associated data interoperability and authentication s
```suggestion
W3C Members that would like to learn more about the motivations that led to this
work may find the <a href="https://solidproject.org/about">About Solid</a> page
useful. The Solid project consists of a
<a href="https://solidproject.org/TR/protocol">draft specification</a> and a
<a href="https://solidproject.org/developers/tools/">suite of implementations,
tools, and libraries</a> for developers.
          </p>

        <p class="mission">
The <strong>mission</strong> of the <a href="">Solid Working Group (LINK TBD)</a>
is to standardize the Solid Protocol and its use of associated data interoperability
and authentication schemes. This effort will culminate in open standards that can be
used by developers of servers and applications to continue to build a rich ecosystem
that returns control of data back to users.
```

2022-12-06 15:27 UTC, TallTed commented on draft-working-group-charter/index.html
> +                The design approach for the Solid specification will continue substantial efforts undertaken previously in the Solid community to specify a set of interoperable protocol standards for
```suggestion
The design approach for the Solid specification will continue substantial efforts
undertaken previously in the Solid community to specify a set of interoperable
protocol standards for enabling the use and development of Solid Pods and
applications across a wide range of use cases.
```

2022-12-06 15:40 UTC, TallTed commented on draft-working-group-charter/index.html
> +                            The Solid specification aims to provide applications with secure and permissioned access to externally stored data in an interoperable way. An overarching design goal of t
```suggestion
The Solid specification aims to provide applications with secure and permissioned
access to externally stored data in an interoperable way. An overarching design goal
of the Solid ecosystem is to be evolvable and to provide fundamental affordances for
decentralised Web applications for information exchange in a way that is secure and
privacy respecting. In this environment, actors allocate identifiers for their
content, shape and store data where they have access to, set access control policies, and use preferred applications and services to achieve them.
```

2022-12-06 18:15 UTC, woutermont commented on draft-working-group-charter/index.html
> +                    The Solid Working Group will deliver the following W3C normative specifications:
Of course, since in concerns a definition list, one could say that in this case the large body of text is a list, which would be okay to introduce with a colon.

2022-12-07 05:24 UTC, TallTed commented on draft-working-group-charter/index.html
> +                    The Solid Working Group will deliver the following W3C normative specifications:
[W3C Style Guide](https://www.w3.org/Guide/manual-of-style/) uses [US English spelling](https://www.w3.org/Guide/manual-of-style/#Spelling) and other US-based guides for [punctuation](https://www.w3.org/Guide/manual-of-style/#Punctuation), so I suggest that the examples of European institutes are irrelevant.

In this case, your latest comment is correct — this introduces a list, hence the propriety of the colon.

2022-12-07 05:29 UTC, TallTed commented on draft-working-group-charter/index.html
> +                Additional technical coordination with the following Groups will be made, per the <a href="https://www.w3.org/Consortium/Process/#WGCharter">W3C Process Document</a>:
Again, the line ending with the colon is introducing a list, albeit a list which the boilerplate split into two sections with `H3` elements (and which could probably lose the first H3 and the entire second section, since the second is commented out).

It might be clearer that this is the case (and that the colon is appropriate) if the H3 elements were converted into an outer UL enclosing the DLs.

2022-12-07 09:49 UTC, woutermont commented on draft-working-group-charter/index.html
> +                    The Solid Working Group will deliver the following W3C normative specifications:
That sais, I am perfectly fine with the colon, given that it is indeed a definition list; so my suggestion can be ignored.

2022-12-07 10:08 UTC, woutermont commented on draft-working-group-charter/index.html
> +                Additional technical coordination with the following Groups will be made, per the <a href="https://www.w3.org/Consortium/Process/#WGCharter">W3C Process Document</a>:
A section is _semantically_ different from a list item, independent of the syntactic boilerplate conversion into HTML. Sections are thematic divisions of the body of a text (or chapter), and only constitute a sequence because of that; i.e. they are lists on a meta-level. Lists in the proper sense, however, are on an object-level: they are already existing divisions, that the author wants to put into writing. Since the colon's semantics apply to the object-level, I would still argue that it is inappropriate to use it at the end of an introduction to sections.

2022-12-07 18:09 UTC, TallTed commented on draft-working-group-charter/index.html
> +                Additional technical coordination with the following Groups will be made, per the <a href="https://www.w3.org/Consortium/Process/#WGCharter">W3C Process Document</a>:
It's not an introduction to sections, even though the currently next HTML tag (which I'm about to suggest be changed) is an H3.  Regrettably, many boilerplates in use by W3C have not been reviewed with a strong focus on proper punctuation, even though the Style Guide (which itself is a relatively new creation) provides clear guidance.

2022-12-07 18:16 UTC, TallTed commented on draft-working-group-charter/index.html
> +        </div> -->
```suggestion
            <div>
                <ul>
                <li id="w3c-coordination">
                W3C Groups

                <dl>
                    <dt>
                        <a href="https://www.w3.org/2017/vc/WG/">Verifiable Credentials Working Group</a>
                    </dt>
                    <dd>
                        Coordination on mechanisms for granting access to resources.
                    </dd>
                    <dt>
                        <a href="https://www.w3.org/2019/did-wg/">DID Working Group</a>
                    </dt>
                    <dd>
                        Coordination on mechanisms for decentralized identifier use in Solid.
                    </dd>
                    <dt>
                        <a href="https://w3c-ccg.github.io/">Credentials Community Group</a>
                    </dt>
                    <dd>
                        Coordination on other specifications related to Decentralized Identifiers.
                    </dd>
                    <dt>
                        <a href="https://www.w3.org/2018/json-ld-wg/">JSON-LD Working Group</a>
                  </dt>
                    <dd>
                        Coordination to ensure that the JSON-LD syntax meets the Solid Working Group's needs.
                    </dd>
                    <dt>
                        <a href="https://www.w3.org/blog/webauthn/">Web Authentication Working Group</a>
                  </dt>
                    <dd>
                        Coordination to ensure that Web Authentication primitives align with Solid principles and aims.
                    </dd>
                </dl>
                </li>
            <!-- 
            </div>

            <div>
            <li id="external-coordination">
            External Groups
            <dl>
                <dt>
                    <a href="https://schema.org">Schema.org</a>
                </dt>
                <dd>
Schema.org should be regularly solicited for reviews and comments on the advancement
of the JSON-LD 1.1 Recommendation.
                </dd>
            </dl>
            </li>
            -->
            </ul>
           </div>
```

2022-12-07 18:19 UTC, TallTed commented on draft-working-group-charter/index.html
> +                Additional technical coordination with the following Groups will be made, per the <a href="https://www.w3.org/Consortium/Process/#WGCharter">W3C Process Document</a>:
In other words, the _semantic_ meaning of HTML tags is not always appropriate for the _semantic_ meaning of the content being presented via that HTML. A great many people use the HTML that makes the most immediate sense for the rendered presentation they desire others to see in their browsers — regardless of the semantics implied by that HTML markup. We might hope that W3 documents were not constructed in such fashion, but that hope will always be forlorn, due to the (strongly desired and encourage!) breadth of the background experience of the Authors and Editors of those documents.

2022-12-07 19:00 UTC, TallTed commented on draft-working-group-charter/index.html
> +                    The Solid Working Group will deliver the following W3C normative specifications:
Regrettably, I have not seen my CMOS hardcopy in a few years. I hope it's in one of the umpteen boxes still packed from my last move, but I may give in and buy a new copy before they're all unpacked. I am not currently interested in registering for an online account, even with their offer of a 30 day free trial.

That said, I'm fairly certain that their advice to _use a colon sparingly_ was in the context of putting it between independent clauses, where I believe a semicolon is appropriate — as may be seen in the quote you provided! — even though they also say that _in some cases either mark may work as well as the other_.

As to their advice that _Sometimes list format may not be the best choice_, I do not believe it pertains to the content of *these* lists, as these _contain multiple levels_ [CMOS 17 § 6.128, as [quoted here](https://eiw365.com/when-to-use-vertical-lists/)]

2022-12-07 19:49 UTC, woutermont commented on draft-working-group-charter/index.html
> +                    The Solid Working Group will deliver the following W3C normative specifications:
I'm aware of their advise on multi-leveled lists, but the discussed list is a single-leveled one (one definition per list item, no nested list in those definitions). Since this single-leveled list has items with a lot more text than a short sentence, it would personally follow CMOS in treating it like a labeled paragraph.

2022-12-08 14:32 UTC, timbl requested changes

2022-12-08 14:32 UTC, timbl commented on draft-working-group-charter/index.html
> +                    Note that the WG may decide, based on editorial and readability considerations, to spin off sections into separate Recommendations.
"separate Recommendations" should be "separate Recommendation track specifications"

2022-12-08 14:32 UTC, timbl commented on draft-working-group-charter/index.html
> +                </p>
How about: "All specifications, regardless of their progress along the W3C process line from WD to Rec, will be given a version number, such as 0.9, which will be incremented like from 0.9 to 0.10 or from 2.9 to 3.0 if there is an incompatible change in the protocol. The required versions of each dependancy will be given in each spec."

2022-12-08 14:49 UTC, woutermont commented on draft-working-group-charter/index.html
> +                        </p>
Good addition :+1: I agree that due regard should be made to existing implementations, and that backward compatibility should be the rule. However, I do believe that in some cases, an exception to that rule could be necessary, and that in those cases it will not be possible to have an intermediate stage supporting both old and new implementations (simply because sometimes these will be mutually contradictive, or would require a huge extra implementation effort). I therefore suggest to leave the last line out.

2022-12-08 14:50 UTC, woutermont commented on draft-working-group-charter/index.html
> +                </p>
Good addition!

2022-12-08 17:33 UTC, TallTed commented on draft-working-group-charter/index.html
> +                </p>
Small tweaks (including spelling correction) to @timbl's suggestion, to increase clarity --

`All specifications, regardless of their progress along the W3C process line from WD to Rec, will be given a version number, such as 0.9, which will be incremented like from 0.9 to 0.10 for minor changes. A major version increment like 2.2 to 3.0 will be used if there is an incompatible change in the protocol. The required versions of each dependency will be given in each spec.`

It may be worth shrinking the discussion of incrementing, and simply referring to [semantic versioning](https://semver.org/).

2022-12-08 17:36 UTC, TallTed commented on draft-working-group-charter/index.html
> +                Additional technical coordination with the following Groups will be made, per the <a href="https://www.w3.org/Consortium/Process/#WGCharter">W3C Process Document</a>:
Please provide a complete quotation of the CMOS "discouragement" to which you refer, as I think "discouragement" is a misunderstanding of what is written there.

2023-01-23 17:22 UTC, barath commented on draft-working-group-charter/index.html
> +            Solid presents several advantages over more traditional architectures for data use by Web services today, including:
Thanks for these formatting suggestions; this and the others will be done using a linter / formatter as a final pass, after this draft is completed.

2023-01-25 03:47 UTC, TallTed commented on draft-working-group-charter/index.html
> +            Solid presents several advantages over more traditional architectures for data use by Web services today, including:
@barath — Given that it's going to be done by an automated tool, I strongly encourage running it sooner than later, as shorter lines make for a MUCH easier editing process, and this should not substantially increase workload by needing to be run again later.

2023-01-25 03:52 UTC, TallTed commented on draft-working-group-charter/index.html
> +                    The Solid Working Group will deliver the following W3C normative specifications:
```suggestion
                    The Solid Working Group will deliver the W3C normative specifications listed below.
```

2023-01-25 03:59 UTC, TallTed commented on draft-working-group-charter/index.html
> +                Additional technical coordination with the following Groups will be made, per the <a href="https://www.w3.org/Consortium/Process/#WGCharter">W3C Process Document</a>:
Different wording helps with the pain of using a full-stop instead of a colon, which I still believe to be the most appropriate punctuation here, even considering all other options.
```suggestion
Per the <a href="https://www.w3.org/Consortium/Process/#WGCharter">W3C Process
	Document</a>, additional technical coordination will be made with the Groups
	listed below.
```

2023-01-25 04:05 UTC, TallTed commented on draft-working-group-charter/index.html
> +            Solid presents several advantages over more traditional architectures for data use by Web services today, including:
Also... I don't think I only changed whitespace, though I believe my other changes were small. GitHub seems to get confused about what's changed by a given suggestion, and so doesn't highlight all changes as desired, in either split or unified view. So, I'll need to do my own manual diff to be sure all my suggestions get picked up. :-/

2023-01-25 14:20 UTC, merged