Add W3C Solid CG Charter
solid/process pull request #323
Opened 2023-07-04 10:58 UTC by csarven

(W3C Solid CG Chair hat on)

I believe it would serve the W3C Solid CG well to have a charter and with a revised simple and clear process.

In this PR, I would like us, the CG members, to consider adopting a charter that can work better going forward. The charter aims to:

* Simplify the process.
* Representative of current working practice.
* Ensure openness and transparency.
* Be approachable as well as informative to newcomers.

It is intended to supersede the process outlined in solid/process (README). The current process in general is:

* Outdated and does not reflect reality.
* Complicated and convoluted.
* Dependent roles (such as the "Editors Team") have been inadequate and inactive for a number of years.

This charter is written in accordance with the W3C Process and aims to remain compatible as much as possible. In addition to following a typical W3C charter outline, the document includes chair elections and work item proposals. Some of this information could be moved to other documents or repositories but it is presented to you as a whole to kick things off. For example, the [Solid Technical Reports Contributing Guide](https://github.com/solid/specification/blob/main/CONTRIBUTING.md) is a thing on its own to have a shared understanding of what's in practice as well as providing detailed information on how individuals can contribute to the CG.

On chairs: the Solid CG would certainly benefit from more chairs representing a wider and more diverse set of voices and perspectives in the community, as well as giving the people who have a demonstrated track record of participation and work in the CG the opportunity to continue their service in a more effective and efficient way, with the proper structures for their work to be meaningful and impactful. For these reasons, when this charter is effective, I intend to arrange an election and open up the option to anyone in the Solid CG. The election process is based on what other CGs have done, and has been working well.

On work items: the Solid CG, within the framework of a W3C CG, generally have a "low bar" to getting stuff done based on open participation and volunteerism. Hence, the process is only intended to help the CG ensure that proposed works are within the scope of the CG, its placement among other work items is understood by group members, and ownership and commitments are stated up front.

This charter is meant to serve as a starting point for the CG to collaborate on the definition and refinement of the processes. Contributions in the form of feedback and requests for clarification (among others) are welcomed and encouraged.

Let's make it so! :)

2023-07-04 13:35 UTC, elf-pavlik commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
I looked at some other CG drafts and final reports and they mostly use
* [W3C Community Contributor License Agreement (CLA) Deed](https://www.w3.org/community/about/process/cla-deed/)
* [W3C Community Final Specification Agreement (FSA) Deed](https://www.w3.org/community/about/process/fsa-deed/)

2023-07-04 14:50 UTC, dmitrizagidulin approved these changes
+1, great work on this!

2023-07-04 14:51 UTC, dmitrizagidulin commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
agreed, W3C CLA license might be good to use here instead

2023-07-04 15:16 UTC, csarven commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
Indeed to publish a W3C "Community Group Report" ( https://www.w3.org/community/about/process/ ). Works under solid/ use the MIT license, including the publications that are under https://solidproject.org/TR/ , and so far they have not been CG Reports. As I understand it, a CG Report document is not required in order to transition to a WG deliverable. I think the Solid CG can still publish CG Reports by simply creating snapshots of particular versions.

If we have consensus on publishing CG Reports in addition to versioned publications, we should distinguish them in the charter (and later in the contributing guide), and thereby clarifying the License and IPR.

2023-07-04 15:55 UTC, elf-pavlik approved these changes

2023-07-04 15:57 UTC, VirginiaBalseiro approved these changes

2023-07-04 21:26 UTC, melvincarvalho commented
-1 Discuss first

https://lists.w3.org/Archives/Public/public-solid/2023Jul/0002.html

2023-07-05 03:22 UTC, elf-pavlik commented
@melvincarvalho not sure if you have noticed that tomorrow's Solid CG weekly meeting has this PR as one of the topics
https://github.com/solid/specification/pull/540/files#diff-7b710cd793bf261c6a16be76e240f1ac6fbea10e3038fc6d88a34753f6e7577dR55

https://lists.w3.org/Archives/Public/public-solid/
This list isn't very active, most Solid CG work happens on GitHub, Matrix, and during online meetings.

2023-07-05 10:36 UTC, melvincarvalho commented
Hi @elf-pavlik,

This is a significant change impacting the entire community group. Keep in mind, only a minor portion of the group frequents the other platforms you mentioned.

Let's finalize the WG Charter while concurrently strategizing on advancing the CG, ensuring full group awareness and consensus. Kindly refrain from merging until that point.

2023-07-05 11:00 UTC, csarven commented on solid-cg-charter.md
> +* Vocabularies for technical reports, test suite design, tests, and test reports.
```suggestion
```

I initially borrowed this topic from the Solid Test Suite Panel's charter: https://github.com/solid/process/blob/main/test-suite-panel-charter.md but I don't think it needs to be mentioned in the Scope. It is something that we are working on as part of the Solid QA initiative, and so covered by evaluation tools / publishing test/technical reports.

2023-07-05 11:03 UTC, csarven commented on solid-cg-charter.md
> +
```suggestion

* [Autonomous Agents on the Web Community Group](https://www.w3.org/groups/cg/webagents)
```

Adding this CG as there is relevancy and interest in collaborating ( https://github.com/solid/specification/pull/529#issuecomment-1568351703 )

2023-07-05 13:26 UTC, woutermont approved these changes

2023-07-05 13:28 UTC, woutermont commented
Perhaps one addendum that could be interesting is how the CG relates to the WG w.r.t. tasks, discussions ...

2023-07-06 16:46 UTC, jeff-zucker commented
I agree that reviewing and defining the CG charter is a necessary step. @csarven - thanks for starting the process.  I believe that we are in a new phase of Solid and that the Community Group should redefine its emphasis to fit that shift.  

We need to put more emphasis on the word "community".  The group should serve to not only facilitate the creation of the specs, but should now also focus on the dissemination and use of the specs.  A dialogue between spec writers and the wider community is needed so that the spec writers can hear use cases and get implementation feedback. It is also needed so that those using Solid can find the current state of the specs as they relate to their work, to get a source of networking with similar projects, and to make their contributions known to the world. 

I also believe that the list of technical topics Sarven provides should be supplemented with topics exploring the social impact of what we are building. While interoperability and the other technical underpinnings are key, we also need feedback about how decisions on those issues impact how Solid plays out in  the real world.  Eventually we might have break-out discussions or sub-groups doing this for various verticals. 

Including these kinds of community and social impact feedback will make the specifications stronger and also give an opportunity for more people to participate in the CG without feeling they need to be a "specifications person" to participate and contribute in an ongoing fashion.  This will hopefully broaden the base of the currently mostly elite group who participate on a regular basis.  As we move into a phase in which real world initiatives will increasingly be appearing, we should gain feedback from those initiatives and support and help publicize them.  This is how we grow a community and an ecosystem.

So I like most of Sarven's proposal as it relates to work supporting spec writers.  I am in favor of adding support for developers and users into the mix which would probably necessitate additional co-chairs for those aspects of the group.

With these thoughts in mind I propose this replacement for the initial section.  I have thoughts on the scope and process as well, but this is enough for now.

# W3C Solid Community Group Charter

The aims of the [Solid Community Group](https://www.w3.org/groups/cg/solid/) and of the [Solid Project](https;//solidproject.org/) it is a part of, are in line with those of the Web itself: empowerment towards "an equitable, informed and interconnected society" [[ethical-web-principles](httpnd choose applications and services to fulfill their needs.

The group supports these goals by

* facilitating work on client-client specifications and apps implementing them
* ensuring the flow of information between spec writers and the global community
* fostering and highlighting real-world uses of Solid
* facilitating new work proposals including both client-client and server-client

The group has three target audiences it aims to support - specification writers, application developers, organizations and individuals using or considering using Solid to meet specific real world needs. The group will foster discussion among these constituencies; including use cases and implementation feedback on both technical performance and social impact. Discussions will explore and describe the interoperability between different classes of products by using Web communication protocols, global identifiers, authentication and authorization mechanisms, data formats and shapes, notifications, and query interfaces. They will also explore social impact of these technologies and Solid-specific approaches to issues such as the delivery of social services, the storage of health and identity records, the monitoring of environmental damage, and similar real world issues that Solid can be applied to.

2023-07-07 13:21 UTC, csarven commented on solid-cg-charter.md
> +
```suggestion

 This group expects to follow the [W3C Web Platform Design Principles](https://www.w3.org/TR/design-principles/) when considering and developing features.
```

2023-07-07 13:27 UTC, csarven commented
Jeff, thank you for sharing your thoughts. I appreciate that you are emphasising important points which are good to clarify CG's goals, and how they overlap and differentiate from the Solid Project and the wider community as a whole.

It is important to keep W3C Solid CG focused on incubation of specifications and implementations. Open standards development naturally includes in- and out-reach communication with various stakeholders.

Please bear with me as I attempt to summarise a few relevant areas that are already part of CG's activities:

On societal impact: the Solid Protocol has a dedicated Societal Impact Considerations section: https://solidproject.org/TR/protocol#societal-impact-review . It is a stub based on a W3C TAG draft. I've introduced this in 2021 so that we are mindful and to get some considerations acknowledged and documented. It ties into and expands on what's stated in Introduction with respect to using the Ethical Web Principles to orient ourselves - "every technical decision has ethical implications both for the end user (short-term) as well as society (long-term)." If need be, a dedicated Task Force could be set up to further investigate and develop these, and share their findings with the CG in the context of a particular technical report, however, it may be better for the wider Solid community to communicate the broader considerations through the Solid Project or via a Solid Team publication.

On adoption and communication: https://github.com/solid/specification/issues/402 places emphasis on challenges we need to take on so that the work is useful to implementers, developers, contributors to TRs (including Work Items), and general public. It is closely related to the Solid QA Initiative: https://solidproject.org/ED/qa (see also [Test Suite Panel Charter](https://github.com/solid/process/blob/main/test-suite-panel-charter.md) as we aim to produce verifiable data (as opposed to resorting to perceptions).

Developing good conformance models defining their classes of products and what constitutes interoperable are key, and they go a long way. While "server-client", "client-client", or "server-server" and so forth, may be generally useful concepts in some contexts, they're not sufficiently specific or meaningful going forward especially when multiple and varying specs with their own products which are attempting to be express interoperability. This is not hypothetical. In the past year or so, we've seen some of the Solid CG specs adopting this view (technically building on the monumental work of the [W3C QA](https://www.w3.org/QA/IG/) Initiative) and improving their conformance models, and ultimately helping us improving our understanding and development of the Solid ecosystem. The current scope covers the key areas with more precision and hints at a range of products that'll materialise. One place to continue this discussion/work is in issue https://github.com/solid/specification/issues/480 .

On developer engagement: please rest assured that specification editors/authors have been working hard and *are* very much engaged. Needless to say, they're also implementers themselves! Editors/authors do regularly seek implementation commitments, gather feedback and integrate, recommend improvements on implementations, answer questions in/around chats and GitHub issues/PRs. Furthermore, you'd pleased to know that there is a recurring topic in CG meetings on WIP implementation feedback for some time now, with fairly regular updates from implementers. I am confident that we'll find ways to improve gathering and reviewing of significant implementer and user feedback from various places. The [Contribution Guide](https://github.com/solid/specification/blob/main/CONTRIBUTING.md) provides some details.

The importance of significant use cases and user stories are still very much core to the CG. As you know, there are some UCR documents (and they can be improved) as well as dedicated repositories. Here is one particular meeting dedicated to reviewing our work around UCs and next steps: https://github.com/solid/specification/blob/main/meetings/2022-12-14.md - Note that it mentions [Priority of Constituencies](https://www.w3.org/TR/design-principles/#priority-of-constituencies) - where it comes up sporadically in CG workspaces - but your comments also reminded me to make sure to incorporate the design principles [into the Charter](https://github.com/solid/process/pull/323/commits/e069abf3b8d6f83fea33fe67db39c7439659aeb3).

That said, I'm with you on continuing on these efforts. I just wanted to emphasise that the considerations that you are highlighting have been taken into account and integral to the CG work (from early on), and reflected in the Charter bar tasks that may be better fit for another grouping . If clarifications are needed we can adjust the language.

2023-07-07 14:43 UTC, VirginiaBalseiro commented
I agree with Sarven that it'd be important to not overlap with the general initiatives of the Solid Project / Team here. I think developer outreach and community building fall under the purview of the Solid Project and/or the Solid team (as reflected in the recent scope discussions). This [PR](https://github.com/solid/team/pull/37) (which has been approved, pending merge) states:

> The Solid Team, headed by Sir Tim Berners-Lee, provides an organisational umbrella for facilitating a strong open source community in support of Solid. This repository contains work of the Solid Team to meet the needs of the [Solid Project](https://solidproject.org/).

We can update this description by adding details as to how we are "facilitating a strong open source community", which can include the activities in scope for the Solid Team, covering many of the activities you mention here around supporting application developers and community outreach. 

As to:

> facilitating work on client-client specifications and apps implementing them
    ensuring the flow of information between spec writers and the global community
    fostering and highlighting real-world uses of Solid
    facilitating new work proposals including both client-client and server-client

I believe some of those goals are already specified in the proposed charter, and I think they don't need to explicitly call out "client-client", "client-server", and so on, since that is already understood from "drafting and incubating proposed technical specifications for further standardization and prototyping and testing implementations" in combination with the scope. 

> ...these kinds of community and social impact feedback will make the specifications stronger and also give an opportunity for more people to participate in the CG without feeling they need to be a "specifications person" to participate and contribute in an ongoing fashion. This will hopefully broaden the base of the currently mostly elite group who participate on a regular basis.

These are all great points. As mentioned above, these are the discussions currently being had in the Solid Team (in the context of defining team scope) around how to improve developer onboarding and community outreach, among other tasks supporting individuals regardless of background to contribute to Solid.

I do believe the points that Jeff is making are important and deserve a revisit in the Solid Team for the Project's mission and goals in the context of the Team's recent scope discussions. Let's take this up in one of the team meetings.

2023-07-07 15:41 UTC, jeff-zucker commented
> I just wanted to emphasise that the considerations that you are highlighting have been taken into account and integral to the CG

I appreciate the work the CG has put in on social impact and implementer feedback and am not trying to say that he CG has done nothing in this arena.  On the other hand, my perception is that the focus is always on the spec writers and not the implementers.  For example, do you have a list of the implementers who have presented at the CG?  Have you taken any steps to network implementers working on related verticals? Do you do any kind of follow-up or publish any information on implementers?

In each of the last two CG meetings there were individuals from implementation projects who did not speak in the meeting.   I corresponded with both of them and have looped one of them into a meeting with a similar project on another continent.  I would like to see this kind of outreach formalized as part of the purpose of the CG.

2023-07-07 16:01 UTC, jeff-zucker commented
> I think developer outreach and community building fall under the purview of the Solid Project and/or the Solid team

I am not categorically against that approach, but I'd like to point out my reasoning for wanting these functions in the CG.   My perception is that there is a big gap between the specifications and the community using them and that both sides of the gap can benefit from a narrowing of the gap.  My perception is that the group who consistently attend the CG is very small and that  the only implementers who stick around are ones who are also spec writers.  My perception is that there are many people whose names are listed as being members of the CG who could be motivated to participate in the CG if they perceived a role for themselves.

2023-07-07 16:19 UTC, jeff-zucker commented
> I think they don't need to explicitly call out "client-client", "client-server"

I think that one of the most significant features of Solid interoperability is the client-client architecture and that it deserves emphasis.  I think that if the WG charter is explicitly about server specifications and the CG charter does not mention client-client, that de-emphasizes a critical part of the architecture.

2023-07-07 18:49 UTC, csarven commented
>my perception is that the focus is always on the spec writers and not the implementers.

Jeff, I won't challenge your perception. Again, on the contrary, what's on public record - the objective reality - is that specification authors and implementers have an open dialogue on a daily basis on publicly accessible GitHub repositories and Gitter/Matrix, among other places. Nor is it ever the intention that "the focus is always on the spec writers and not the implementers". What we are doing is not architecture astronomy. As mentioned in the Introduction, "the consensus on the technical designs are informed by common use cases, implementation experience, and use." You're welcome to challenge that or share your perceptions. Here is even a dedicated meeting for implementer feedback: https://github.com/solid/specification/blob/main/meetings/2021-10-21.md . We'll strive to do better. But to be clear, the group is not pretending to be physically and emotionally doing everything everywhere all at once.

>For example, do you have a list of the implementers who have presented at the CG?

You're to first to ask about this. Yes, not only a list but their descriptions can be obtained from the minutes. Implementers are not limited to the presentations at the CG or CG meeting either. That information is also available from chats, GitHub, e.g., issues, UC surveys, call for implementations, mailing list, and even conferences and research documents. If "a list" is deemed to be useful, I can only encourage you to write automated scripts to generate the data.

That aside, we have taken several steps further than just compiling a list. For instance, the Solid QA aims "to give authors of technical reports **and** software implementers confidence that they can rely on the Solid ecosystem to deliver on the promise of interoperability based on open standards." Emphasis mine. Those are not just words or accidental. All of how we get there is detailed / WIP in https://solidproject.org/ED/qa where various stakeholders come together to meet our goals, and you'll get far knowledge than a "list of the implementers". So, Solid QA is another area to get involved in because that's where we work towards showing implementation reports and adoption based on data, as opposed to perceptions.

>Have you taken any steps to network implementers working on related verticals?

I think that question is a touch too vague in these circles. To re-emphasise, not everything is on the CG to take on, which includes "network implementers" above and beyond what the CG is already doing. The kind of networking you may be curious about may be better handled via the Solid Team. Two of the Solid Team meetings that I know of touch on this topic: 

https://github.com/solid/team/blob/main/meetings/2023-05-10.md
https://github.com/solid/team/blob/main/meetings/2023-05-17.md

>Do you do any kind of follow-up or publish any information on implementers?

See my points on Solid QA, and the work that goes towards test reports and implementation reports. There are unofficial test reports about implementations, e.g., https://solidservers.org/ - FYI, it is unofficial because the consensus was that Solid QA will detail how to produce "official" publications. Moreover, some of the specification and test contributors have in fact went out and reached implementers on what they are doing correctly and what could be improved in their implementations. To my understanding, in addition to public communication, there is also private communication towards that end.

>In each of the last two CG meetings there were individuals from implementation projects who did not speak in the meeting. I corresponded with both of them and have looped one of them into a meeting with a similar project on another continent. I would like to see this kind of outreach formalized as part of the purpose of the CG.

I applaud your efforts to reaching out. I will encourage anyone to follow in your footsteps. In general, outreach is already part of works that CGs do, and evidently you were able to accomplish outreach without any special formalisation.

As you've undoubtedly noted, there is a whole Introductions topic in the meetings and it is also part of the [meetings template](https://github.com/solid/specification/blob/main/meetings/template.md). The groups makes sure to welcome new names. If they choose to not speak, they're still welcome to participate in the call. Likewise, people are not obligated to speak or present their work, and newcomers might prefer to have space to explore rather than being contacted directly immediately. There are nuances to all of this. 

---

>My perception is that there are many people whose names are listed as being members of the CG who could be motivated to participate in the CG if they perceived a role for themselves.

Sure, that is a possibility. As far as I can tell, it comes down to picking up tasks and getting things done, over handing out roles and hoping for the best. I've seen countless times folks sign their name up or want credit/privileges/authority but have fallen short on delivering. Yet, I've seen folks over the years making remarkable contributions day in day out without asking for special roles. There is data.

---

>I think that one of the most significant features of Solid interoperability is the client-client architecture and that it deserves emphasis.

I believe what's intended with "client-client" in the context of Solid, is abundantly covered under the Scope. That's besides the notion of "client-client" not particularly well-defined or common out there, but please do share commonly accepted references that'd be meaningful for the Solid CG. If and when there is a question of whether a proposed work item fits under the Scope, the charter already explains ways to incorporate or reject.

2023-07-07 20:11 UTC, jeff-zucker commented
@csarven thank you for the pointers to the excellent existing work of the CG on engagement with implementers.  I have no criticisms of existing work.  What I am saying is that  we are entering a new phase which calls for new layers of organization.  

For example, you write 

> not only a list but their descriptions can be obtained from the minutes. Implementers are not limited to the presentations at the CG or CG meeting either. That information is also available from chats, GitHub, e.g., issues, UC surveys, call for implementations, mailing list, and even conferences and research documents. If "a list" is deemed to be useful, I can only encourage you to write automated scripts to generate the data.

That is fantastic that you and the CG have created all of that.  Thanks and congratulations!  It is exactly that list that would be generated by that data I am asking about.  I am aware that I can gather such a list and have actually started.  I believe that the gathering and dissemination of that data should not be left to me as an individual but should be a recognized function of the CG.   I believe that there needs to be a  focus on community engagement that makes data like this available to a wider audience.  This has never been an aim of the CG so it is not faulting the CG to say it hasn't been done.  But now that we're in a new phase, it needs to be done.  

This example also points to one of the reasons I believe that the community engagement function should live in the CG.  Why should anyone have to go back and gather all of that data rather than it being a part of the process to create a registry of information as we go?   And why shouldn't we have tracks and meetings aimed at the wider community?  Yes, for sure you've already done some, but I am talking about a real effort for community engagement where dissemination  and use of Solid is the focus rather than creation of Solid.

> you were able to accomplish outreach without any special formalisation

Again, I think this should be an institutional function, not left to an individual. 

> [people engage] without asking for special roles

 When I said "if they perceived a role for themselves" I didn't mean a named role, I meant perceived that they could learn and contribute.

2023-07-08 13:08 UTC, elf-pavlik commented
Given we need at least a clear line between

* Solid WG
* Solid CG

Do we need to further distinguish Solid CG from

* Solid Team
* Solid Project

?

I'm worried that we may end up with time same issues as with the panels (some thoughts in #324)

--------------

Yesterday I had a short call with someone who is going to work on a project which aims at improving the Solid app development experience as well as the user onboarding experience. I'd like to share here something that Solid CG/Team/Project/Community/Ecosystem/... needs to address.

I think there is a justified urge to make user onboarding as seamless as possible. At the same time, I think there is a thin line between making onboarding as smooth and as honest as possible and making it dumb and prone to long-term negative perceptions of Solid.

For example:

* a person (or small indie team) gets excited about an idea for their solid application
* they develop it quickly and start offering it to users
* to make onboarding dumb simple, they deploy open-source WebID hosting, solid storage, and solid-oidc provider and offer it as one-click onboarding step directly from their app
* bunch of users find their app, hear it is a Solid app and go with their dumb simple on-click join-the-party experience
* one year later the person's (or small indie team's) enthusiasm runs out, maybe because others developed alternative Solid apps, each with greater popularity
* the person/team decides to ditch the project, together with user webids and their storages

I think this is a realistic scenario, where the temptation to oversimply user onboarding leads to a bunch of users might felt burned by Solid and ending up very hesitant to have anything to do with it again.

IMO Solid CG (if that's who takes long-term stewardship over Solid) can address it by recommending and cautioning about the user onboarding process. Providing clear and multilingual information about pros and cons of using one's own domain vs. relying on domains offered by providers of various Solid services.
We could even take inspiration from projects like https://tosdr.org/ and https://w3id.org/ to help users make educated choices when they decide to put their trust in Solid. 


----


This is only an example, the main need it exemplifies is a long-term stewardship over Solid, user/developer experience and their perception of Solid and trust in it.

2023-07-08 14:46 UTC, csarven commented on solid-cg-charter.md
> +
```suggestion
As per W3C [structures for groups](https://www.w3.org/groups/) and [W3C Process](https://www.w3.org/Consortium/Process/), the Community Group will maintain its focus on incubating technical reports and software implementations within the [Scope](#Scope) of the charter, with the aim to transfer mature works to be further worked on under W3C Recommendation Tracks.

```

2023-07-08 14:46 UTC, csarven commented on solid-cg-charter.md
> +
```suggestion
* CG Work Items that have transitioned to a deliverable of an active Working Group.

```

2023-07-08 14:48 UTC, csarven commented
Melvin, Wouter, thank you for your recommendations, and I have updated the introduction and Out of Scope https://github.com/solid/process/commit/790add55188a703a94d67485f15d4a381f5391e0 . We can revisit the relationships between CG and WG once for example the Solid WG comes into existence.

2023-07-08 14:50 UTC, csarven commented
Jeff, thank you for acknowledging CG's activities, and bearing with me to differentiate perceptions/misinformation from what's on public record.

We're not reinventing the CG here and there is no justification to add "new layers of organization" without having demonstrated or developed trust in an open and transparent fashion.

The proposed charter is a clarification of CG's current activities and what's generally ahead. In general the mission and the problem space remains the same.

There is nothing stopping you or anyone else from suggesting and/or implementing these improvements you bring up around dissemination of data in the current state of things or the proposed charter. I fail to see how new layers of organisation are needed or desirable in order to compile data and make it available to a wider audience. Moreover, I have already explained numerous existing CG activities, including efforts in Solid QA, as well as what's planned. 

All in all, I believe there are no blockers in the proposed charter for people to take up certain tasks and introduce improvements to different aspects of the CG's activities. I believe focusing on actions like these, rather than getting tied up in "layers of organization" and related is a more positive approach that promotes trust, collaboration and a drama-free work environment. 

Do you have an objection to any part of the charter in particular?

2023-07-08 16:56 UTC, jeff-zucker commented
> Do you have an objection to any part of the charter in particular?

My objection is to a community group that has no plan or named function to grow and include a wider community.  

You believe these functions should fall under the Solid Team, not the CG.  I would like to hear other opinions on that (hey lurkers, chime in!) and will bring it up at the next Team meeting.

2023-07-08 16:59 UTC, jeff-zucker requested changes
There are major issues about what the scope of the CG is.  I strongly object to committing this PR until they have been thoroughly discussed.

2023-07-08 17:43 UTC, VirginiaBalseiro commented
I believe the Solid Team and the CG of course have shared goals, but their tasks and activities are distinct. 

The structures and processes that are already in place in the Solid Team make it a well-suited place for the kind of activities being discussed around developer support / community outreach. In addition, the Team has also [recently](https://github.com/solid/team/blob/main/meetings/2023-05-10.md) [agreed](https://github.com/solid/team/blob/main/meetings/2023-05-17.md) to bring many of these topics under Team's scope. 

I don't see a need for the CG to absorb ST, or even some of its activities, but rather keep in mind that the two groups do not exist in a vacuum and interact / inform each other's work, and potentially find better and improved ways to enable and enhance this communication.

2023-07-08 17:44 UTC, woutermont commented
Alright, this 'lurker' will throw in his 2c.

@jeff-zucker, I wholeheartedly agree that outreach is of the utmost importance for the Solid Project to succeed. We NEED interest groups that consider new tech, dreamers that invent new applications, nerds that hack stuff together... their enthousiasm and feedback is our oxigen. Building a community including those people is of the utmost importance.

However, that community comes together under the umbrella of the Solid Project, and thus building it to succeed in their missions is in the first place a goal of the Solid Project. 

The W3C Solid CG is a W3C Community Group group, i.e. a group that works as an incubation pool for open W3C standards. It makes sense that this group has a stronger focus on spec-work than the Solid Project as a whole. It also makes sense that this CG can tap into the community building efforts of the Solid Project, rather than having such efforts as part their own main goals.

My opinion is therefore that @csarven's proposal for the charter is a good one, and that calls for more community building efforts should be addressed towards the Solid Project, rather than the CG.

2023-07-08 18:05 UTC, jeff-zucker commented
@elf-pavlik  wrote : 

> Do we need to further distinguish Solid CG from
> 
> * Solid Team
> * Solid Project

Great question.  What do you see as the role of the Team in relation to the CG?

> long-term stewardship over Solid, user/developer experience, and their perception of Solid and trust in it.

Yes, please.

2023-07-08 18:15 UTC, jeff-zucker commented
@woutermont thanks for your thoughts

> It makes sense that this group has a stronger focus on spec-work than the Solid Project as a whole. 

I fully agree.  I do not want to see the spec work impeded or backgrounded, I want to see it more completely integrated with the other work of the Project.  This proposal as written isolates the CG from the rest of the Project in terms of scope.  And, as @elf-pavlik points out, without clarifying any relationship to the Project.

2023-07-08 18:40 UTC, woutermont commented
Re @elf-pavlik's question comment, I believe the Solid Project is the true long-term steward of Solid, the Solid Team is a core group of people that invest a courageous amount of effort towards the goals of the Solid Project, and the Solid GC is the project's incubation pool towards an open standard.

2023-07-08 18:44 UTC, csarven commented on solid-cg-charter.md
> +
```suggestion

The Solid community with various stakeholders comes together under the umbrella of the Solid Project, and thus the W3C Solid Community Group interacts and coordinates with the Project's organisation as a whole to help inform the work with the needs of the wider community. 

```

2023-07-08 18:48 UTC, csarven commented
Thank you for your suggestions Jeff, Pavlik, Wouter, Virginia. Updated the introduction to clarify relationship to the Solid Project and emphasis on importance of community: https://github.com/solid/process/commit/4171fe44cf4442625aa2acd8697ad05506d5d0dc .

2023-07-08 18:52 UTC, woutermont commented
Thanks for that addition re Solid Project, @csarven!

@jeff-zucker, wdyt? Can we settle on this and maybe take some further steps towards (1) more networking and (2) a better network->spec information stream in the Solid Project?

2023-07-08 18:54 UTC, jeff-zucker commented
@VirginiaBalseiro - thanks for your thoughts

> keep in mind that the two groups do not exist in a vacuum and interact / inform each other's work, and potentially find better and improved ways to enable and enhance this communication.

I agree and I feel both the Project and the CG need to clarify their relationship and reach a common understanding about how "interact/inform" happens.  To say the specs are over here and the community is over there and not provide a bridge is, in my mind, folly.

2023-07-08 19:22 UTC, woutermont commented
I think the latest changes address that concern adequately.

2023-07-08 19:26 UTC, jeff-zucker commented on solid-cg-charter.md
> +
> interacts and coordinates with

I think the mechanism for that needs  to be explicitly stated.

>  to help inform the work with the needs of the wider community

The purpose of the interaction and coordination is not just to inform specification writers about the needs of the wider community but to inform the wider community how to implement and use the specifications.  

If the CG scope eliminates both gathering input from and producing output for the wider community, I think it must be explicit about how it intends to participate in those activities.

2023-07-08 19:43 UTC, VirginiaBalseiro commented on solid-cg-charter.md
> +
> eliminates both gathering input from and producing output

I believe it does the opposite of eliminating. We can clarify on output - as in, informing back to the community about developments in the specifications, and as mentioned, there are already CG activities that help in that regard.

> I think the mechanism for that needs to be explicitly stated.

The text states that the CG communicates with the Project organization. This is the mechanism. Details do not to be specified here (partly because this is something we agreed above we'd need to properly define and improve, as per my comment, but primarily because it is not necessary).

2023-07-08 20:00 UTC, jeff-zucker commented on solid-cg-charter.md
> +
Yes, the CG has produced much valuable output. My full statement  was "output for the wider community". For example : holding workshops for implementers explaining a given spec change - is that under the purview of the CG or the Project and if under the Project, what is CG's role? For sure the specs themselves and the github pages are chock full with excellent materials. That is a different statement from "the wider community is aware of and able to understand a lot of excellent materials". To go from one to the other takes coordination.

2023-07-08 20:02 UTC, jeff-zucker commented
> I think the latest changes address that concern adequately (on the CG front, at least).

Unfortunately not from my point of view.  See https://github.com/solid/process/pull/323/files/790add55188a703a94d67485f15d4a381f5391e0#r1257330030

2023-07-08 20:05 UTC, woutermont commented on solid-cg-charter.md
> +
> The purpose of the interaction and coordination is not just to inform specification writers about the needs of the wider community but to inform the wider community how to implement and use the specifications and who is doing the implementing for what purpose.

I disagree. It is a important that the community is informed about the spec, but the CG can/should not do more than provide adequate primers. The Team or other community members can/should use this info to spread the word, bit we cannot expect the CG (a spec-focussed organ) to bear the responsibility for every detail any implementer wants to know.

> If the CG scope eliminates both gathering input from and producing output for the wider community, I think it must be explicit about how it intends to participate in those activities.

This disregards the latest change entirely. The proposed charter now clearly states that gathering input form the Project's community is a must. How this exactly needs to happen, is not a matter for a charter. The same goes for every other listed goal: the charter lists the goal, but it does not impose the way the goal needs to be reached.

2023-07-08 20:19 UTC, jeff-zucker commented
@csarven Can you clarify one of your sentences in the scope -

> Discussion of out-of-scope solutions should be limited to elaborating upon technological advantages/disadvantages.

What is an out-of-scope solution in this context?  What is the purpose of limiting the discussion to technical issues?

2023-07-09 09:41 UTC, csarven commented
Out of Scope solutions typically refer to proposals, changes, discussions, and feedback that do not align with or expand upon the Architecture of the World Wide Web. These solutions are also considered to be inconsistent with the Ethical Web Principles and Web Platform Design Principles. For instance, when suggestions involving crytpocurrency, Web3, or NFT technologies are presented, it is understood that while the group may allow discussions about the technological differences, these ideas will not be accepted as official work items or lead to modifications of existing work items based on such solutions, regardless of their advantages or disadvantages. The first item mentioned as out of scope: "the relative merits of various economic, political, or sociological theories" also applies here.

Hence, "limiting the discussion" is to ensure that the group stays focused on its mission and context, and delivers work items that fall within its defined scope. Solid CG adopts a specific approach to decentralisation, which should not be confused with or assumed to cover all possible topics and ideas.

2023-07-09 16:27 UTC, jeff-zucker commented
@csarven - thanks for the clarification.  You might want to look at where that sentence sits in the spec.  It follows right after the point about marketing and I was confused whether the non-tech rule applied to it or to it alone and apparently the answer is neither.  Perhaps just a matter of a missing bullet point.

2023-07-10 11:41 UTC, csarven commented on solid-cg-charter.md
> +* Only one call for no-confidence, for one chair, may be in process at any given time. Priority shall be given to the first such vote to be publicly called. Any subsequent public calls must wait unti
```suggestion
* Only one call for no-confidence, for one chair, may be in process at any given time. Priority shall be given to the first such vote to be publicly called. Any subsequent public calls must wait until any previous recalls are resolved, then must start with private communication as described above.

## Amendments to this Charter

* Chairs may propose amendments to the charter by asking for a call for principled objections to the new charter. If, after a period of two weeks, no principled objections have been presented by a current member of the group, the new charter is approved.
* If a principled objection is posted to the mailing list or expressed in a regular call, then the chairs may either drop the amendment or proceed with a public vote.
* A public vote for a new charter must be called by the chairs within two weeks of the principled objection.
* Such a vote will be open for two weeks, with ballots cast via the group’s public mailing list. Each member of the group may cast one ballot, “yea” or “nay”. A new charter must receive “yea” on two-thirds of the votes cast in the ranked choice vote, and the total votes cast must represent 5% or greater of the group membership, to pass.
* The group will use the amendment process for any substantive changes to the goals, scope, deliverables, decision process or rules for amending the charter.
* Changes to the Coordination does not constitute an amendment to the charter that requires a rechartering vote.

```

2023-07-10 11:43 UTC, csarven commented on solid-cg-charter.md
> +
```suggestion

* Created: 2023-07-04
* Modified: 2023-07-10
* Version: 1.0

```

2023-07-10 12:00 UTC, csarven commented
Jeff, once again, I respect your enthusiasm and considerations to look for ways to improve the community, as well as this charter. We have shared interests on cultivating a diverse and healthy Solid community, we just need to work towards a common method.

The range of the initiative you are seeking - *beyond* CG's current activities - does not particularly fall under the purview of a CG as a "topic", not just in Solid CG but it is not typical for W3C CGs/WGs. However, it is well-suited for a group that focuses specifically on endeavors aimed at supporting and growing the wider community, by coordinating across various teams (e.g., Solid CG, proposed Solid WG, DEI Team, Solid MIT, SolidLabs, .. Women of Solid) and stakeholders (e.g., projects, implementers, users), such as the Solid Team, as per the recently revised and acknowledged Solid Team Scope. If need be, along the lines of a "community outreach" sub-group/project can be set up within the Project organisation.

Communication and coordination with the CG is a given, as it has been established in this discussion. This has been acknowledged in the text taking your and others' suggestions into account. There are already numerous CG activities aiming at this coordination. We certainly can improve and expand on these, but it is not a task for the CG to carry out wide developer/community outreach activities (such as workshops/conferences, hackathons, webinars, and the like). As others have mentioned, these kinds of details are typically not described in CG/WG charters.

I sincerely hope that this addresses (some of) your concerns but you're still welcome to make concrete change requests, and can certainly use your feedback to improve the language.

2023-07-10 14:23 UTC, woutermont commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
Re the license: given that the only formal requirement seems to be that final reports of the CG fall under a W3C FSA license, is there any other advantage/incentive to switch all current MIT-licensed contributions to the W3C CLA?

2023-07-10 14:24 UTC, woutermont approved these changes
Approving latest changes. License still needs to be resolved though.

2023-07-10 14:26 UTC, jeff-zucker commented
@csarven thank you for pointing out the many areas of overlap in our concerns.  We both want to see a wider and more diverse Solid community and I intend to continue working on that goal regardless of how functions are split between various organizations.  

This discussion itself is a complete illustration of the problem.  Who is participating - 100% Euro-American, caucasian, advanced-degree, spec writers with one woman and zero people other than those who have already been involved in the specs (I least of you, for sure).  And where is the discussion held - in the same difficult to penetrate github discussions which are part of the very problem as many people over the years have described how difficult it is for non-experts to penetrate the mass of github writings.  Is github great for holding transparent technical discussions? Yes.  Is it great for holding democratic and representative discussions?  Absolutely not.

> Communication and coordination with the CG is a given

That's what you say.  What does the Team who would be other side of this coordination say? I think there are many unresolved issues and that the proposed charter will serve to isolate the spec writers even further from the wider community.  I think I've said most of what I can say about this here so I won't continue belaboring the point. I will wait until the Team has addressed these issues.

2023-07-10 14:56 UTC, jeff-zucker commented
> From a distance and with the little time I have available to comment on this, this seems good enough.
> 
> I am intrigued about what "client-client" means.

Type indexes are one example.  There is no specification relating to servers that says anything about the indexes.  The proposed specification says that clients (apps) which want to be interoperable with other clients should write triples of a certain kind in a certain place where other clients can discover them.  The interoperability is established through communications between clients and therefore client-client.

2023-07-10 16:12 UTC, VirginiaBalseiro commented
> 100% Euro-American, caucasian, advanced-degree

None of this applies to me.

> with one woman

This does, although a bit reductive :)

>  I will wait until the Team has addressed these issues.

The Team *has in fact* been discussing community outreach, how to be more welcoming to newcomers, how to make content more widely available, networking events (such a Solid World), among other initiatives, for a long time now, and again, it has recently been acknowledged as in the scope of Solid Team. 

I think it would be more productive to use Team time to figure out how to bridge between CG and wider community in a more effective way, just as we've acknowledged to do so as part of the Scope for other groupings under the Solid Project.

2023-07-10 16:42 UTC, jeff-zucker commented
> None of this applies to me.

I am very sorry for making inappropriate generalizations.  Do you deny my general point that this is a very elite group in relation to the wider community?

> I think it would be more productive to use Team time to figure out how to bridge between CG and wider community in a more effective way,

I agree.  That is what I will wait for - the Team to discuss what relationship it has with the CG and how it will create bridges going forward.

2023-07-10 16:49 UTC, VirginiaBalseiro commented
> I agree. That is what I will wait for - the Team to discuss what relationship it has with the CG and how it will create bridges going forward.

In that case, does that need to be a blocker on this charter? As ST will be discussing improving coordination across the board and not the scope of the charter.

2023-07-10 16:52 UTC, woutermont commented
@VirginiaBalseiro, could you give us some reference of where this was discussed, and/or where we can bring up the remaining concerns? 

@jeff-zucker, while I acknowledge that we should strive for diversity in all our efforts, I fail to see how most of us being caucasian Euro-Americans with an advanced degree impacts the coordination between the Solid Project and the CG. Both @csarven and myself, two people who might fit your description (not 100% sure about Sarven but I sure do), have on multiple times done efforts to increase awareness and ease of joining the Solid movement. Recent examples I can think of (mind you, I've been away for a while) are making/keeping the event calendar up to date, and my PRs to the Solid Project web pages. Things just move slowly; we all get frustrated by that from time to time.

2023-07-10 17:02 UTC, VirginiaBalseiro commented
> @VirginiaBalseiro, could you give us some reference of where this was discussed, and/or where we can bring up the remaining concerns?

These topics have been discussed in recent Solid team meetings around the Team's scope:

* https://github.com/solid/team/blob/main/meetings/2023-04-19.md
* https://github.com/solid/team/blob/main/meetings/2023-05-03.md
* https://github.com/solid/team/blob/main/meetings/2023-05-10.md
* https://github.com/solid/team/blob/main/meetings/2023-05-17.md
* https://github.com/solid/team/blob/main/meetings/2023-05-24.md

A good place to bring up these concerns would be: https://github.com/solid/team/issues

2023-07-10 17:06 UTC, VirginiaBalseiro commented
> Do you deny my general point that this is a very elite group in relation to the wider community?

Actually, it is not. The [community survey](https://virginiabalseiro.github.io/survey/) we held last year  showed that a majority of the respondents are white, male, and with higher education backgrounds. 

So the distribution we are seeing in this particular PR is consistent with this data. 

I do agree that the tech industry in general and Solid (among many, many other projects or communities) have an astounding lack of diversity. We do have the structures to work on these issues (Solid DEIT team), and we definitely should make it a priority to do so in the Solid Project.

2023-07-10 17:07 UTC, bblfish commented
@jeff-zucker wrote:
> This discussion itself is a complete illustration of the problem. Who is participating - 100% Euro-American, caucasian, advanced-degree, spec writers with one woman and zero people other than those who have already been involved in the specs (I least of you, for sure).

I just want to say that bringing in race and sexual differences here is completely inappropriate. 

> And where is the discussion held - in the same difficult to penetrate github discussions which are part of the very problem as many people over the years have described how difficult it is for non-experts to penetrate the mass of github writings. Is github great for holding transparent technical discussions? Yes. Is it great for holding democratic and representative discussions? Absolutely not.

I don't think GitHub is not ideal either. Mailing lists can also be overwhelming as I learned by participating in the IETF Atom syntax and protocols in 2005 and on.

2023-07-10 17:16 UTC, jeff-zucker commented
> @VirginiaBalseiro :  In that case, does that need to be a blocker on this charter? As ST will be discussing improving coordination across the board and not the scope of the charter.

No I am not comfortable with approving this charter (or other major re-arrangements within Solid) until I have heard from the Team.  As a matter of principle I would like to hear from the wider community before approving this charter.  If others on the Team agree with y'all that the CG should not include community engagement as part of its function,  and if others on the Team are comfortable with the only relationship between the Team and the CG being a stated intention to coordinate, I will remove my objection and do everything in my power to help  build a bridge between the CG and the community.

2023-07-10 17:30 UTC, jeff-zucker commented
> I want to say that bringing in race and sexual differences here is entirely inappropriate. Let us stick with specs, implementations and rational discussions, open to all of course.
> 

Well I  certainly botched my introduction of the topic (apologies again @VirginiaBalseiro) and I won't compound that by talking further about it now.

2023-07-10 17:47 UTC, jeff-zucker commented
@woutermont wrote
> Both @csarven and myself .. have on multiple times done efforts to increase awareness and ease of joining the Solid movement.

Absolutely!  Thank you both.  I do not in *any* way meant to imply that there is an intention to be exclusive.  I know that Sarven and Virginia have both worked tirelessly to increase diversity.  Thank you to all of you.  I very much appreciate your efforts.

2023-07-10 17:50 UTC, woutermont commented
Re discussion platforms, the perfect one does not exist. For the purpose of spec-writing (the core task of the CG and its panels), GitHub does an excelent job (much better than mailing lists, fora, chats etc.). For gathering wide input, it does indeed much less of a good job, but for that we have panel meetings. Steering people towards those is a difficult but important task.

One thing I have learned is that the more communication platforms are supported, the less coordination of input there is. We currently have GitHub, Gitter/Matrix, the meetings, the forum, the mailing list ... (I am probably even forgetting something.) It wouldn't hurt community coordination to focus on one or two less.

2023-07-10 18:21 UTC, jeff-zucker commented
> Members of the Team do not have a heavier say in this than any other
 
But they have a say, and I will wait to hear it.

> everyone who chipped in is okay with it except you

And, though I botched how I said it,  my point is that everyone who has chipped in so far is from the select group of people already participating in the specifications and does not include input from anyone else in the community and that I am not prepared to agree to the charter until I have heard input from a wider selection of the community. 

And, if, after I have heard further input, I am still in the minority, I will, as I said, withdraw my objection.

2023-07-10 23:38 UTC, csarven commented
Let's continue to get more people to review the charter, and I encourage everyone to reach out to other CG members to review the PR.

Rest assured that we'll make sure to have a "last call" to gather remaining feedback before making the CG charter official. Using the W3C Process as guidance towards a review period here, it could be at least 28 days. So, on 2023-07-25 let's make sure to nudge folks again. On one of the CG weekly meetings after 2023-08-01, we can merge if all feedback is formally addressed.

Unless every member in the CG supports the charter, there won't be "unanimity" as per W3C Process. I doubt that we will have unanimity since that's generally difficult and can be impractical - mind you the Solid CG currently has "271 participants representing 91 organizations" :) but then again unanimity is not required. We need to reach reasonable consensus about the CG charter, i.e., to be useful enough above all things, and I'm confident we'll achieve that.

2023-07-11 08:55 UTC, timea-solid commented
From what I gather, the charter proposal follows tightly the W3C way of naming and doing things. 
What I understood from reading it, is that the CG has a quite 'technical' managerial role. If I want to write a spec or propose a technical solution, the CG is where I would seek guidance. I can expect help in how to write a spec. And if there is momentum, at the end, be listed here https://solidproject.org/TR/. Is this correct?

>  The group will aim to give authors of technical reports and software implementers confidence that they can rely on the Solid ecosystem to deliver on the promise of interoperability based on open standards.

The above is ambiguous to me.
The CG does not do any marketing for my idea of a new spec but I can trust "that I can rely on the Solid ecosystem to deliver on the promise of interoperability based on open standards". What does 'rely' mean? Are you referring to all the guidelines for writing specs? or that the CG's scope is also to make sure all the listed deliverables on https://solidproject.org/TR/ are 'based on open standards 'and 'deliver on the promise of interoperability'?

> The Solid community with various stakeholders comes together under the umbrella of the Solid Project, and thus the W3C Solid Community Group interacts and coordinates with the Project's organisation as a whole to help inform the work with the needs of the wider community. 

The above sounds like there are regular meetings with all entities, subgroups and so on (Solid Team, DEI team, panels..) where an exchange happens of information around needs and action items. 
For example, can I expect something like the following: if I have a new spec proposal and I am looking for participants, would the CG mention in these 'interactions and coordination with the Project's organisation' that there is this new spec on some topic? But then again this sounds like marketing. 
Anyhow, how would that work? And which entity, in general, looks at the problem that some panels are dormant or losing participants and motivation?

I am not saying the CG should do all these. Some parts could be less ambiguous yes(see above) but otherwise, I think it fully fits in the W3C way of things. I am mentioning all these here, as a holistic view, because most of the same people here are also on the other teams...

2023-07-11 11:13 UTC, csarven commented
Timea, thank you for all this feedback and I think you've highlighted areas where we can improve.

>Is this correct?

Yes, that's generally correct. As mentioned, contributing guide / processes is detailed elsewhere. The charter gives a direction.

>What does 'rely' mean? Are you referring to all the guidelines for writing specs? or that the CG's scope is also to make sure all the listed deliverables on https://solidproject.org/TR/ are 'based on open standards 'and 'deliver on the promise of interoperability'?

A bit of both. The text is originally taken from the [Solid Test Suite Panel Charter](https://github.com/solid/process/blob/main/test-suite-panel-charter.md) (see its Goals for longer description why it exists/necessary) working on the [Solid QA](https://solidproject.org/ED/qa) Initiative where it sets the ground rules to "promise" interoperability, communicating adoption, as well as integrating feedback. I can see that context is not clear even though it is given in the Scope. So, I've updated the language to clarify this: https://github.com/solid/process/pull/323/commits/7a8cfc55edaaf9de26252976fa8365d7c884bdc7 .

<details open="">
<summary>Quoting the TSP Charter Goals about the intentions:</summary>

>The Test Suite Panel will operate with a mutual understanding between contributors to technical reports, test suite software maintainers, and software implementers by following a cooperation process for the advancement of the Solid platform.

>Writing tests in a way that allows implementations to conform to the requirements of a technical report gives Solid projects confidence that their software is compatible with other implementations. This in turn gives authors of technical reports and software implementers confidence that they can rely on the Solid ecosystem to deliver on the promise of interoperability based on open standards. Implementation and interoperability experience can be verified by reporting on implementations passing open test suites.
</details>

---

> The above sounds like there are regular meetings with all entities, subgroups and so on (Solid Team, DEI team, panels..) where an exchange happens of information around needs and action items. Is this correct?

Generally yes but the details are not specified in a charter. This merely acknowledges that the CG is part of a larger story working towards realising the Solid vision. CG does not - and cannot - dictate who, how, when exactly all that happens, in the same way that other groups cannot dictate what CG does. However, since discussions are in the open, we strive for mutual understanding. Information flows in different directions. For example, when we took up a topic originally in a CG meeting, we reached an agreement that the solution was beneficial to the whole Solid community, so the CG took it upon itself to have an action item to follow up, e.g.: https://github.com/solid/solidproject.org/pull/755 . And there countless of these examples on public record. Hence, coordination is evidently already possible with the current open and transparent structures in place for the benefit of the wider community.

> If I have a new spec proposal and I am looking for participants, would the CG mention in these 'interactions and coordination with the Project's organisation' that there is a new spec? Then again, this sounds like marketing.

Just want to be clear that the intention is creating awareness and advancing development, not at all "marketing".

The "New Work Item Proposal" outlines how new proposals can be brought forward to the CG as well as making sure that there are owners and commitments made. This is essentially the minimal steps necessary to register the existence of an idea or a call for work and gather shared interests. Once such "significant unit of information" can be referenced (URI), it can be used by anyone (both in and outside of the CG) to gather additional support.

>Anyhow, how would that work? And which entity, in general, looks at the problem that some panels are dormant or losing participants and motivation? And how can newcomers be helped on this topics too?

Going forward, we'll transition from "Panels" per se to "Task Forces" which will be more concrete to solving specific and narrower problems. See also original proposal at https://github.com/solid/specification/pull/458#issue-1390870735 and Pavlik's recent considerations at https://github.com/solid/process/issues/324 . The CG will assist and navigate newcomers in solving particular problems in their area of interest. Just to be clear, your question is excellent and it deserves a longer response. Motivation and engagement is certainly a challenge when work is done in the open and on volunteer-basis, and we are definitely not the only group facing such a challenge. It is a task for each of us to strive to motivate, encourage, and enable fellow members of the group to stay engaged and doing good work, while at the same time being mindful of individual concerns or limitations.

>I am not saying the CG should do all these. Some parts could be less ambiguous yes(see above) but otherwise, I think it fully fits in the W3C way of things. I am mentioning all these here, as a holistic view, because most of the same people I see here are also on the other teams... and maybe it can be brought up in the according meetings.
It is difficult for me to grasp the Solid puzzle of where the CG fits in. 

> I can only suspect that this was the reason why the Solid Team and Project were brought up too.

I also think that's generally how things organically happened considering the goals of the Solid Project as a whole. The CG alone cannot "fix the Web". The notion that CG can't take on wide-reaching activities (that is above and beyond what the CG has been doing) of the Solid Project that are suited for another team has been acknowledged in this PR's discussion.

>Also, giving feedback on this long discussion here is not easy. Maybe try to divide and conquer.

I generally agree, but unfortunately such is the nature of async work. We are indeed using the CG weekly meetings to summarize and make it easier to follow the discussion.

I hope the above is an adequate response to your inquiries but please let me know if further clarifications are required. Thanks again for raising points that lead to updating the charter for the better.

2023-07-11 14:51 UTC, michielbdejong approved these changes
Great!

2023-07-12 03:23 UTC, CxRes commented
Here is the dissonance I see. Solid CG charter wants to restrict to specification work and allied activities. But CG meeting seems to be the main place where folks interested in Solid congregate. At least, I am not aware of a separate Solid “project meeting”. So it is in not unnatural to ask for the wider issues that @jeff-zucker raises to be brought under the ambit CG charter. 

With the creation of the WG, Solid community needs to think really hard about how it wants to organize the various functions and make them explicit, so that everyone can work synergetically to bring about the outcomes we are after.

PS: I have many criticisms of the way Solid is being currently managed and how the concerns are being hand waved (typically with extremely long responses), but I have no interest or bandwidth for participating in the "commotion" above. The community as a whole needs to do more listening and less responding!

2023-07-12 06:22 UTC, woutermont commented
> CG meeting seems to be the main place where folks interested in Solid congregate. 

The meetings usually see only a handful of (the same) people. Matrix, the forum, and even GitHub have a lot more community interaction going on.

2023-07-12 07:02 UTC, CxRes commented
>The meetings usually see only a handful of (the same) people. Matrix, the forum, and even GitHub have a lot more community interaction going on.

True, but you are completely missing the point of the argument! 

+ Human interaction (speech) is qualitatively different from chat and forums.
+ What is the designated place to talk (not type) to people involved in Solid about the larger issues, if it is not the CG meeting? 
+ If the CG charter is limited to spec work (and its first order cause and effects), presumably these should not be issues for discussion in the CG meeting. Where should one take the larger considerations (for Pete's sake don't say forums/chat/Github)? Is it even sensible to divorce or fragment these discussions as separate from the spec work?

2023-07-12 09:07 UTC, woutermont commented
> you are completely missing the point of the argument!

An argument only works if its premises are correct. So thanks for patiently separating it into less assuming questions.

> What is the designated place to talk (not type) to people involved in Solid about the larger issues, if it is not the CG meeting? [...] If the CG charter is limited to spec work (and its first order cause and effects), presumably these should not be issues for discussion in the CG meeting. Where should one take the larger considerations (for Pete's sake don't say forums/chat/Github)?

You also seem to have missed the point I made earlier in this discussion: that is not for the CG to decide on. The Project as a whole has a large number of communicaton channels (too many if you ask me). If some members of the community feel like they need another one (e.g. because of a qualitative difference), they are free to [A] start one or [B] ask the Team to start one.

> Is it even sensible to divorce or fragment these discussions as separate from the spec work?

Absolutely! The CG's discussions are focussed on making the spec progress. They therefore have as input everything that can help towards that goal, and as output changes to the spec, and the process of these discussions is to somehow get from input to output. Now, there are a lot of topics fall neither under this process, nor under its input or output:

- I want to use the Community Server to do xyz...
- There is a typo on the website; please correct it...
- We built a disruptive innovative platform using Solid and we are so excited!...
- Hey Rahul, how was your holiday?...
- I have built an app with technology abc; can I make it work with Solid?...
- Is Solid also a legal framework?...
- Should my Solid app have a beautiful URL?...
- I'm using Inrupt libraries, but the following code snippet won't work...
- Solid has a lack of diversity; let's discuss possible strategies...
- Is Penny down, or is it just me?...
- We'd like to present our latest research on the possible economical impact of Solid...

Most of these topics can i.m.o. be handled adequately on an asynchronous communication channel. For those would prefer a video call, Solid World is often a good alternative, or a similar channel could be created by the Team. 

Having these topics in a CG call is simply not a good idea because
1. The people that are actually there for CG work will lose time (and interest) having to sit through irrelevant topics.
1. The people that come specifically for those topics will in many cases be bored and put off by the spec work.
1. The handful of people that are really interested in both are perfectly capable of joining two different calls.

2023-07-12 10:50 UTC, CxRes commented
God there are too many examples (some of which can have direct impact on spec work and hence may need to be considered in CG meetings even with a restricted agenda). Please, no grandstanding to make your point.

The thing about empathetic listening is: 
+ Do you understand what @jeff-zucker's pain is? Is it possible to articulate it in your own words or even come up with a better version of his argument?
+ Do you believe that things are well managed in the Solid project, that issues he raised, even if they don't go into the CG charter, are not worthy of being raised in the process of drawing up a charter?
+ In the current setup, when such discussions need to be conducted in person, where should anyone go? If they are being discussed in Solid CG meeting, as is the case today, isn't that the first forum where anyone will raise such matters?
+ If you do not like his suggestions, is it possible for you to suggest pragmatic strategies to cohesively and comprehensively address the issues he is raising (Not, lets start another call? Or, why don't you go to the forum?)? Or do you think these issues have no place in Solid itself and no effect on Solid specifications?  

Thing is, I am not asking for immediate answers, but asking everyone to take this opportunity for some serious introspection. Why not let these questions (not this comment, but the entire thread) sit with you for **one week**, and then post an answer!

2023-07-12 13:29 UTC, VirginiaBalseiro commented
@CxRes:

The points Jeff raised about community outreach are universally agreed upon in this thread. The only disagreement lies in determining the appropriate group to effectively address those needs.

Many comments in this thread have focused on clarifying what a Community Group is and isn't, how it differs from other groups, and defining the scope of the CG. However, it's important to note that this doesn't imply the CG is seeking to restrict itself to specification work alone. Nor does it mean that the Solid Project as a whole is unwilling to address these needs through the appropriate channels. Rather, the CG needs to have defined goals and scope, and it cannot and should not take on all activities related to the community's needs. There is already an existing team with a scope that includes these activities, making it the most suitable place to develop and improve upon these endeavors.

I would also like to address the topic of communication. I understand the importance of empathetic listening and acknowledging people's needs. However, the conflict here stems from differing strategies rather than a disagreement about the needs themselves (which we all seem to agree on!). Therefore, it would be helpful to refocus the conversation on the strategies.

Moreover, it's crucial to recognize that not only are our own needs valid and deserving of being heard, but others' needs are equally important. Disagreeing on strategies does not mean the other person isn't listening. Let me provide a specific example: you mentioned you consider giving a long response to be "hand-waiving," but this perspective doesn't promote compassionate and productive dialogue. People invest time in writing lengthy responses because they genuinely want to help or express their own needs. Empathetic listening should work both ways, and assuming that anyone who disagrees with me is seeking to provoke conflicts hinders the potential for productive exchanges.

2023-07-12 14:06 UTC, woutermont commented
Thanks @VirginiaBalseiro.

I indeed believe that we all agree on the need for community outreach. The length of this discussion may have blurred the distinct concerns that play:

1. Should the CG try to gather as much spec-relevant input/feedback as possible from the broader community?

Definitely, like any W3C CG. The Editors already do this by putting panel meetings on the event calendar, announcing each meeting in the Matrix chat, asking for an update to the Project's 'Contributing' page, and now also by posting calls for feedback in a pinned forum topic.

2. Should the GC communicate its output (spec changes) to the broader community?

Definitely, like any W3C CG. The Editors do this by putting new versions of specs on the TR overview. I think they could also consider to ping the abovementioned channels when merging PRs with major changes, to communicate a little more finegrained on the output dimension.

3. Should the GC be responsible for the broader communication of the Solid Project?

In my opinion, and the opinion of most people that weighed in, as well as the definition of a W3C CG, it should not. As we tried to point out in this discussion, and @VirginiaBalseiro so nicely put:

> There is already an existing team with a scope that includes [activities related to the community's needs], making it the most suitable place to develop and improve upon these endeavors.

2023-07-12 15:10 UTC, CxRes commented
Unfortunately, my argument here were not being fully understood, especially in the context of Solid process. I hope the CG call has clarified my stance. I strongly agree with Laurens that all organization functions need to be assigned with clarity.

2023-07-12 15:37 UTC, CxRes commented
Since the charter itself is a response to the deficiencies of the Solid Process (and the formation of WG), it just makes sense that we address all the other shortcomings of the Solid process in one fell swoop (and not just communication).

2023-07-12 16:29 UTC, woutermont commented
I don't see why that would "just make sense." 🤔 

The GC can only update it's own aspects of the Process. It has neither the responsibility nor the justification to decide on the other matters. If people would like to see other changes to the Process, they should take that up with the Solid Team, but that should not impede the CG from progressing with its charter.

2023-07-12 17:06 UTC, jeff-zucker commented
I would like to clarify that what I am proposing is not *instead* of the work of the current CG, it is *in addition*.  One possibility might be that we would have three sub-teams - specifications, implementers/users, developers which would each hold separate discussions and there would be a fourth regular discussion for everyone.  There would be a slight bump in work for the specs part of the CG in that they would need to attend the all-team meetings but it would not place the work of outreach and engagement on the spec sub-team, others would need to step in to fulfill those functions.  Maybe the sub-team on the specs would have its own charter and its own rules about scope of its discussions.  By having the three sub-teams under the same umbrella, we would provide an established framework for sharing between the groups and make it crystal clear the scope of the different discussions and work.  

If the CG decides that it wants to remain exclusively devoted to the specs without the other elements of the community, I propose that it change its name to the "Solid Specifications Group" to indicate that is not the place for general discussion, community building, networking or anything other than providing feedback and getting clarity on the specifications.  To call itself "The Solid Community Group" is quite misleading if the current spec-exclusive focus continues to be the case.

2023-07-12 18:14 UTC, csarven commented
Jeff, with all due respect, and I have to repeat this: specifications are not developed in a vacuum and there is already an ongoing conversation between various hats/stakeholders. Some data/URLs were mentioned. This is acknowledged in this thread in the context of what a W3C CG entails. The CG does not see "specifications, implementers/users, developers" as separate entities or subteams. That's not how things are or ever intended. So, calling it as such or trying to form them as separate entities will likely have the opposite effect to getting things done. We work together. Some of us have multiple "hats". Adding new layers of org in the CG to address some deep rooted Solid Project concerns above and beyond what we are doing introduces unnecessary complications. Various layers of orgs/roles in the Solid Process have been considered inadequate and ineffective, and dare I say, harmful! So, the last thing we want is some promise that our problems are going to be solved or improvements are going to be made by repeating the exact same mistakes. This charter proposal builds on lessons learnt from what did not work.

I don't want to rename the W3C Solid CG ... in the same way we're unlikely to rename the WG proposal to "W3C Solid Specifications WG". Solid is not the first/last "community" out there.. and I can't even think of any other CG/WG out there that includes the word "Specifications" as part of its title. This is not to say that CG's are strictly limited to "specifications" either.

Creating a "W3C **Business Group**" may cover some of the things you are keen about just to help frame the conversation / expectations, and it may serve well for the wider Solid Project too. That needs further discussion ... and again, or some other grouping under the Solid Project to unite various teams/groups across the board. It is not up to the Solid CG to do wide Solid matters when its focus is to... incubate specs in a nutshell. Neither would it be the case that CG would ever have the authority or access to conduct such matters properly, fairly, in the open and in an transparent manner.

We're in 80+ comments now and majority of it went into reviewing perceptions and solutions for what generally falls outside of the CG. Again, outside the list or category of things that are beyond what the CG is already doing. Do you feel that we've given these ideas enough consideration and energy? I'm genuinely interested in facilitating consensus here on the CG charter, and we also need to be practical. It includes a limit to what has received sufficient amount of deliberation. I do not want the conversation to stop, but I would also like us to move forward. Have the group use its energy in other aspects of the charter, or even on "day to day" concerns of the CG. I don't feel that now or this charter is a place to pitch new untested ideas. Is adopting of the ideas or waiting for Solid Team to have an opinion on what CG is/isn't, should/shouldn't do.. or what the Solid Team can/can't do, who can put their foot down and not... is really the way to be productive? I find your criteria for lifting the objection only "if" and "if" and "if" and... complicated and unfair to the whole CG. As I see it, this charter is necessary and sufficiently useful as is - fingers crossed. It can be and should be updated in the future! I'm still optimistic that we'll find a way to move ahead together.

2023-07-13 03:08 UTC, CxRes commented
@woutermont I think we agree that in drawing up CG charter, we are amending the Solid Process and delineating some responsibilities from them to be the primary domain of CG. Now there are other things covered in the Solid Process that (creators, administration etc.) all of which were, if all else fails and/or when human interaction required, could be brought up in Solid CG meetings and presumably will not be after the charter. Ergo, it is an excellent time to revisit them and assign a new home before the charter is drawn up. In other words, "just makes sense"!

@csarven I hate to pick another "robust" discussion with you, but it falls squarely in the remit of this discussion that we address the side effects of making the CG charter. What happens to the remainder of the Solid Process (since that was informing CG actions uptil now)? If I am not supposed to bring those issues up with in CG meeting where am I supposed to go? It is ironic that you seem to treat the CG charter as its own thing, but you are creating this CG charter in the solid/process repo. These issues need explicit clarification by amending the process README in this PR.

2023-07-13 09:25 UTC, woutermont commented
@CxRes, simply repeating your opinion does not make it more true, I'm afraid 🤷 

@jeff-zucker, thanks for providing some possible ways forward 👍 

Personally, I'm not a fan of having subteams within the CG. Spec-writers, implementers and users should not be separated when it comes to discussions on the progress of Solid. **They are all welcome to discuss work items together in the existing meetings.** That is what @csarven and I have tried to emphasize.

I do agree that **it might be beneficial to add an <ins>extra (bi)weekly meeting</ins> to the Solid ecosystem**, where implementers and users can come together to talk about the broader context: introductions, app ideas/presentations, helping users, guiding implementers etc. Whenever some topic results in an issue regarding some spec work item, people in these meetings could be pointed to the relevant CG (panel) meeting.

To give some examples:

- Someone built something using Solid, did some economical research on Solid ...
=> They can present their work on the Solid Project meeting.

- Someone wants to discuss Solid and diversity, legal frameworks, beautiful URLs ...
=> They can do so in the Solid Project meeting.

- Someone wants to use Solid / the Community Server / Inrupt's libraries ... to do xyz. 
=> They can ask for help in the Solid Project meeting.

- Some of those research, use cases, legal considerations ... could have impact on the specs.
=> They can discuss that in the Solid CG/WG (depending on the work item).

Re the naming of those groups, I think it is fairly clear that CG and WG refer to W3C specification groups. We could call the extra meeting something like the <ins>'Solid Project meeting'</ins>, to emphasize its all-encompassing nature. But if you insist, I don't think _informally_ calling it the <ins>'Spec Incubator Group'</ins> or something wouldn't hurt clarity. ('Specifications Group' would be ambiguous between CG and WG.)

2023-07-13 10:34 UTC, CxRes commented
@woutermont I am getting extremely frustrated at you repeatedly mischaracterizing my statements (an explanation in a different way is not repetition, it is trying to get the point across with a different emphasis. Also, even if it were repetition, somehow you can repeat stuff in your comments and grandstand, but only my doing so is a problem). Even when I pointed those flaws out myself, I have done them in general, never in the first person.

You are simply taking advantage of my politeness and me trying to explain in the most patient way possible. It is also clear to me that you are utterly unknowledgeable on systems engineering and the concept of designing systems holistically (systems can be anything where number of parts come together to perform a function, including communities) holistically. It is not possible for me argue with you in good faith. 

Also, I know others will jump to your defence, insinuating as previously that I somehow do not understand things (without any attempt to understand why I am saying something). Congratulations on outshouting me, You have won! I cannot bother to contribute to a community/process that is tolerant of such double standards. This is very much violative of Solid's own community rules!

2023-07-13 10:48 UTC, woutermont commented
@CxRes, the frustration is mutual, yet I never assume to to know what you have or haven't understood, or what your level of knowledge is on cerrtain topics. In any case, it was not my intention to call you out, so if you had that impression, I sincerely offer my apologies. I simply wanted to point out that your comment contained no new argument or alternative path to a consensus (which I do try in all of my contributions). The heat I feel from your side in this debate might have influenced my wording in a negative way. Again, I am sorry for that.

I also created https://github.com/solid/process/issues/325, in good faith, to try and address your issues with the remainder of the Process. I hope it helps to (slowly) find a resolution to this discussion.

2023-07-13 11:09 UTC, CxRes commented
@woutermont What "heat" are you even talking about (I am absolutely genuinely befuddled by that comment)? After the meeting last evening (until my previous comment, obviously), I thought our differences were resolved, we generally had consensus and only that we needed to look at Solid process (only point of difference between our stance). Our comments last night (my time) were cordial, as one can plainly see. Are you holding on to some resentment about our discussion before the CG meeting?

2023-07-13 11:23 UTC, woutermont commented
@CxRes I'll PM you on Matrix, not to make this discussion our private chat ...

2023-07-13 18:18 UTC, csarven commented
>What happens to the remainder of the Solid Process (since that was informing CG actions uptil now)?

Not entirely. It will continue to exist of course but will be modified (see my comments below). I think we also briefly touched on this at the end of 2023-07-12 meeting: https://github.com/solid/specification/blob/main/meetings/2023-07-12.md#add-w3c-solid-cg-charter (we had to end the call so the minutes don't capture all the detail).

>If I am not supposed to bring those issues up with in CG meeting where am I supposed to go?

IIRC, the Solid Process has so far been discussed in CG and in Solid Team meetings. CG has always been open to discussing any aspect of the Solid Process but we have also deferred those discussions to Solid Team meetings (although member or invite only at the moment), or following up specific matters in various repositories.

>It is ironic that you seem to treat the CG charter as its own thing, but you are creating this CG charter in the solid/process repo.

Excellent question! If memory serves me well, I've introduced the charter in this repository for a couple of reasons:

* the charter needs to be its own document.
* this repository includes other charters.
* to keep it close to the Solid Process in order to help people contrast and understand the context easier.
* it is a starting point, serves just as well as anywhere else for the time being but it can be moved [1].

In my initial comment, I also mentioned this:

>Some of this information could be moved to other documents or repositories but it is presented to you as a whole to kick things off.

[1] I propose that the canonical CG charter is published at Solid CG's pages at w3.org (e.g., https://www.w3.org/community/solid/charter/ and linked from https://www.w3.org/groups/cg/solid/ ) so that it is easily findable by anyone navigating to Solid CG on the W3C website. Future drafts/versions of the charter can be worked on in this repository. No doubt it can be in another repository if so desired.

>These issues need explicit clarification by amending the process README in this PR.

Yes, we are trying to get there a step at a time. As mentioned in my first comment (context being the Solid CG):

>It is intended to supersede the process outlined in solid/process (README).

Wouter also clarified this earlier: "The [CG] can only update it's own aspects of the Process."

I gave an additional reason in https://github.com/solid/specification/blob/main/meetings/2023-07-05.md#add-w3c-solid-cg-charter :

>I found no point in revising the old process since it would lead to a re-write anyway.

Again, the CG charter needs to be its own document.

So, once the CG charter is a "self-describing document" (just as a WG charter says what it needs to say about itself in its own document) it is a simple(r) process to modify the Solid Process. The Solid Team is working on clarifying its Scope, and so I suspect that will also cause an update to the Solid Process.

2023-07-13 18:28 UTC, csarven commented
I would like to remind us all that we abide by the [Solid Code of Conduct](https://github.com/solid/process/blob/main/code-of-conduct.md) and [Positive Work Environment at W3C: Code of Ethics and Professional Conduct](https://www.w3.org/Consortium/cepc/). One particular expected behaviour is noteworthy here:

>Treat everyone with respect. We are a large community of people who are passionate about our work, sometimes holding strong opinions and beliefs. We are committed to dealing with each other with courtesy, respect, and dignity at all times. Misunderstandings and disagreements do happen. When conflicts arise, we are expected to resolve them maintaining that courtesy, respect, and dignity, even when emotions are heightened.

2023-07-14 16:48 UTC, jaxoncreed reviewed
Everything seems pretty reasonable. I'd just like some clarification around the communication section.

2023-07-14 16:48 UTC, jaxoncreed commented on solid-cg-charter.md
> +Technical discussions for this Community Group are conducted in public: the meeting minutes from teleconference and face-to-face meetings will be archived for public review, and technical discussions
Just a quick point of clarification. Would it be allowable to collaborate on a spec proposal/open implementation in private and bring it to the CG once it's ready to present, knowing that this does not guarantee an endorsement from the CG and might require massive changes?

Sometimes doing that is required so that work doesn't get gummed down in the minutia of public opinion before it's ready.

2023-07-14 17:23 UTC, csarven commented on solid-cg-charter.md
> +Technical discussions for this Community Group are conducted in public: the meeting minutes from teleconference and face-to-face meetings will be archived for public review, and technical discussions
The text "drafts of specifications" in the charter is referring to what's acknowledged as a CG Work Item. So, that work is carried out in public. As to anything prior to becoming a CG Work Item, there are no requirements - they can be conducted in private or public.

Hope that answers your question. Do you think it'll be clearer if we replaced "Drafts of specifications" with "Work Items" (above, line 104) or something else?

2023-07-18 14:58 UTC, gibsonf1 commented
I've read the proposed Charter and comments above, and very much like the focused scope of the Charter which I think is needed for really moving forward effectively.  @jeff-zucker comments about bringing in implementers etc are also good, and @csarven 's idea "Creating a "W3C Business Group" may cover some of the things you are keen about just to help frame the conversation / expectations, and it may serve well for the wider Solid Project too."  I think would be excellent.

One thing I've been worried about is that there is a tendency to define Solid as being about personal data only.  The Charter does not make that distinction, which is very good.  I thinking having a Business Group of some kind would be an excellent way to make clear that this is not personal only, but running businesses with all the benefits that the Solid approach to data can provide.  And this kind of group could provide the kind of feedback and networking Jeff was trying to encourage, such that then there could be feedback relevant to the CG from the Business Group when it arises.

2023-07-19 11:04 UTC, csarven commented on solid-cg-charter.md
> +  5. What actions are you taking to make this work item accessible to a non-technical audience?
```suggestion
[The work item process is outlined here](https://github.com/solid/specification/blob/main/CONTRIBUTING.md#work-items).
```

2023-07-19 14:10 UTC, timbl commented
I am concerned that this PR makes many changes at once.  Normally we make a sequence of independent changes.  The PR process in github is not well suited to a large set of changes -- hence the huge amount of discussion and contention.     

The group of the Editors may have been dysfunctional, true, but the work of others, such as the Creators and the Administrators has been  valuable and important.  Running the systems and updating content is important.  Perhaps they and the Solid Team should be considered part of the Solid Project under the Solid Team - and the Community Group considered a separate thing.

2023-07-19 14:23 UTC, elf-pavlik commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
Maybe we could request guidance from someone at https://www.w3.org/staff/legal/ ?

2023-07-19 16:50 UTC, pchampin requested changes

2023-07-19 16:50 UTC, pchampin commented on solid-cg-charter.md
> +* Such a vote will be open for two weeks, with ballots cast via the group’s public mailing list. Each member of the group may cast one ballot, “yea” or “nay”. A new charter must receive “yea” on two-
```suggestion
* Chairs may propose amendments to the charter by asking for a call for principled objections to the new charter. If, after a period of two weeks, no principled objections have been presented by a current participant of the group, the new charter is approved.
* If a principled objection is posted to the mailing list or expressed in a regular call, then the chairs may either drop the amendment or proceed with a public vote.
* A public vote for a new charter must be called by the chairs within two weeks of the principled objection.
* Such a vote will be open for two weeks, with ballots cast via the group’s public mailing list. Each participant of the group may cast one ballot, “yea” or “nay”. A new charter must receive “yea” on two-thirds of the votes cast in the ranked choice vote, and the total votes cast must represent 5% or greater of the group participants, to pass.
```

2023-07-19 19:08 UTC, csarven commented on solid-cg-charter.md
> +The Community Group members appoints (and re-appoints) Chairs for the group.
Good catch! Borrowed this from CCG's Charter and it slipped in.

2023-07-19 19:56 UTC, csarven commented
Tim,

Solid Editors were the only role that had direct involvement with the specification development process. Creators and Administrators are already roles in the Solid Team, and they operate independently from the W3C Solid Community Group but still all under the umbrella of the Solid Project.

2023-07-20 14:14 UTC, jaxoncreed commented on solid-cg-charter.md
> +Technical discussions for this Community Group are conducted in public: the meeting minutes from teleconference and face-to-face meetings will be archived for public review, and technical discussions
Sounds good.

2023-07-20 14:14 UTC, jaxoncreed approved these changes

2023-07-20 18:28 UTC, damooo commented
Looks great for me.

2023-07-20 22:55 UTC, renoirb approved these changes
Looking good. But that's my first time doing any review on a charter PR (instead of a technical one).

2023-07-20 22:55 UTC, renoirb commented on solid-cg-charter.md
> +
(I'm aware it's solved, just making a note for later)
 
> > I think the mechanism for that needs to be explicitly stated.
> 
> The text states that the CG communicates with the Project organization. This is the mechanism. Details do not need to be specified here (...).

What would be useful is to clarify at least that this CG is part of W3C.  As in it's not something separate like WHATWG was/is.

2023-07-20 22:55 UTC, renoirb commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
Would there be also for the UI layer metadata. As in a way to allow implementation of a view without forcing a library, yet allowing one implementation that we can replace. The metadata be used in either case. (Hoping that makes sense. Unsure if that's the same as "Autonomous Web Agent")

2023-07-20 22:55 UTC, renoirb commented on solid-cg-charter.md
> +To afford asynchronous decisions and organizational deliberation, any resolution (including publication decisions) taken in a face-to-face meeting or teleconference will be considered provisional. A
I'm unsure if that's where we should read about how to get a vote, like in an organization, what constitutes a "Quorom". Or it's just based on technical merit of the people collaborating until the end of grace period. <aside>(technical merit over politics <em title="For the Win">FTW</em>!)</aside>

2023-07-20 23:07 UTC, renoirb commented on solid-cg-charter.md
> +To afford asynchronous decisions and organizational deliberation, any resolution (including publication decisions) taken in a face-to-face meeting or teleconference will be considered provisional. A
I'd like to see a definition of what "*incubation*" and what it means and how it works.

2023-07-21 01:37 UTC, gibsonf1 approved these changes
Excellent work

2023-07-21 08:58 UTC, melvincarvalho commented
> There are major issues about what the scope of the CG is. I strongly object to committing this PR until they have been thoroughly discussed.

Indeed.  It would be more reasonable to address this matter after the WG is voted upon and the structure of the two groups is established.

2023-07-21 14:30 UTC, woutermont commented
> [jeff-zucker:] There are major issues about what the scope of the CG is. I strongly object to committing this PR until they have been thoroughly discussed.

> [melvincarvalho:] Indeed. It would be more reasonable to address this matter after the WG is voted upon and the structure of the two groups is established.

1. This PR, as well as the two meetings we had about it, IS the way in which it is being "thoroughly discussed".
1. In the discussion up till now, the only issue that has been raised regarding scope is that about communication.
1. There is (to my knowledge) no reason why the CG's charter should be influenced by the existence or structure of the WG. They are two separate structures with clear objectives defined by the W3C.

> [timbl:] I am concerned that this PR makes many changes at once. Normally we make a sequence of independent changes. The PR process in github is not well suited to a large set of changes -- hence the huge amount of discussion and contention.

> [melvincarvalho:] 💯 Agree. Split it into different parts, and get agreement on each part

1. The PR mostly describes the way we are already working today; as such, it does hardly make "many changes". 
1. Taking the time to actually read the comments in the PR will reveal that the "huge amount of discussion and contention" is in fact limited to two main points up till now: the scope regarding communication, and the effect on the process document, on both of which there has been worked to resolve them.
1. Fact is that 9 people already agree on the whole, so I fail to see why we should split it.

2023-07-24 07:28 UTC, csarven commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
I want to understand better, can you please elaborate? Perhaps a few use cases? There is some UI work in [SolidOS](https://github.com/SolidOS/) that seems to be related to what you're saying. See also [http://www.w3.org/ns/ui](An ontology for User Interface description, Hints and Forms) . I wonder if we should boost this more into the Scope. It generally has to do with what some refer to "client-client" specifications but we can be more specific on the UI aspect. Will raise this in an upcoming CG call to check with everyone in the meantime.

2023-07-24 08:21 UTC, csarven commented on solid-cg-charter.md
> +To afford asynchronous decisions and organizational deliberation, any resolution (including publication decisions) taken in a face-to-face meeting or teleconference will be considered provisional. A
Updated to refer to W3C's Incubation and some paraphrasing: https://github.com/solid/process/pull/323/commits/fbabbcaa8abf7037c01dc42a7a4e40cc80dee740 . Does that improve/clarify?

2023-07-24 08:44 UTC, csarven commented on solid-cg-charter.md
> +To afford asynchronous decisions and organizational deliberation, any resolution (including publication decisions) taken in a face-to-face meeting or teleconference will be considered provisional. A
This *generally* has to do with "major" organisational or technical decisions. When for example voting is needed, there'd be more time for participants to respond. In practise, often rough consensus helps to move things forward without having to wait for wide consensus or seek unanimity, or perform ceremonies so to speak. Chairs and editors are expected to act in good faith and use their best judgement as to when to seek group consensus for certain decisions and when to go ahead with "day to day" stuff. That said, some of this process is detailed and can be further detailed in the Contributing Guide.

I will follow-up with a proposal based on [Classes of Changes](https://www.w3.org/2023/Process-20230612/#correction-classes), e.g., class 1-2 changes can be done at the discretion of the editors of a specification with the understanding that changes can be easily followed. So, a PR may be made and merged immediately, and the comments or commit messages providing sufficient detail / references to any agreements made elsewhere. Ditto timeframe per change class.

Hope this response is satisfactory. I suggest that we follow-up on process-level details elsewhere, but do let me know if charter-level clarification is needed here.

2023-07-24 16:46 UTC, TallTed commented on solid-cg-charter.md
> +To afford asynchronous decisions and organizational deliberation, any resolution (including publication decisions) taken in a face-to-face meeting or teleconference will be considered provisional. A
```suggestion
To afford asynchronous decisions and organizational deliberation, any resolution (including publication decisions) taken in a face-to-face meeting or teleconference will be considered provisional. A call for consensus (CfC) will be issued for all resolutions (for example, via email, GitHub issue, or web-based survey), with a response period of five to ten working days, depending on the chair's evaluation of the group consensus on the issue. If no objections are raised by the end of the response period, the resolution will be considered to have consensus as a resolution of the Community Group.
```

2023-07-24 16:48 UTC, TallTed commented on solid-cg-charter.md
> +As per W3C [structures for groups](https://www.w3.org/groups/) and [W3C Process](https://www.w3.org/Consortium/Process/), the Community Group will maintain its focus on [incubating](https://www.w3.or
```suggestion
As per W3C [structures for groups](https://www.w3.org/groups/) and [W3C Process](https://www.w3.org/Consortium/Process/), the Community Group will maintain its focus on [incubating](https://www.w3.org/Guide/incubation) technical reports, prototyping software, and testing implementations within the [Scope](#Scope) of the charter, with the aim of advancing mature works to the W3C Recommendation track in a Working Group.
```

2023-07-24 19:19 UTC, damooo approved these changes

2023-07-25 11:29 UTC, woutermont approved these changes

2023-07-25 14:12 UTC, melvincarvalho commented
The CG is 272 people.  Only a fraction have voted for this way of working, and even then, it is far from unanimous (several down votes).  So, this document should be opt-in, for the 11 out of 272 people that wish to work that way.

Chairing the CG should be a separate new topic, and should go out to the whole 272 members CG for an extended period.  I personally think that voting is far too easily gamed.  I much prefer @timbl to select chairs to create a balance, that represents diverse views.  Something like my ideal chair selection would be:  jeff / timea / elf.

2023-07-25 14:37 UTC, melvincarvalho commented
> Creating a "W3C Business Group" may cover some of the things you are keen about just to help frame the conversation / expectations, and it may serve well for the wider Solid Project too

This could be a good idea

Woring Group -- oriented towards spec writers
Business Group -- oriented towards businesses in the space, full time employees
Community Group -- more casual, including part time contributors, and open source implementers

Different people allowed to work in different ways, leading to a diverse set of participants

But, the WG should be settled first, the chairs, the people, the work items.  Then see what is left for the other 1/2 groups.

2023-07-25 18:21 UTC, jeff-zucker approved these changes

2023-07-26 14:18 UTC, TallTed commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
@pchampin -- Please do as suggested by @elf-pavlik (get comment from [W3C Legal](https://www.w3.org/staff/legal/)).

2023-07-26 14:24 UTC, TallTed approved these changes
Pending approval by and/or modulo change requests for the license/IPR details from W3C Legal, looks pretty good overall. Certainly more detailed than most CGs in which I've been involved!

2023-07-26 14:39 UTC, elf-pavlik commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
Extracted into a separate issue: https://github.com/solid/process/issues/327

2023-07-26 18:00 UTC, woutermont commented
To repeat the calculation I made during today's CG meeting: I went through the past year's Gitter/Matrix conversations and GitHub comments related to solid/specification, and counted in each shortly over 50 active participants. That would mean that about 25% of the people who are (still) engaged approved the proposal.

2023-07-26 18:27 UTC, woutermont commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
> Would there be also for the UI layer metadata. As in a way to allow implementation of a view without forcing a library, yet allowing one implementation that we can replace. The metadata be used in either case. (Hoping that makes sense. Unsure if that's the same as "Autonomous Web Agent")

@renoirb, I'm going to interpret some of your words; please tell me if I'm right or not.

Your question concerns some agent (I suppose some application) which would use certain metadata (about a resource) that should be sufficient to render a UI display (of that resource) without relying on some proprietary library (i.e. other than a general library for interpreting that metadata). The question then is whether the CG scope includes looking into this metadata. Is this correct?

My questions to you would then be:

- Do you suppose this would require other metadata than that which describes what kind of resource we are talking about?

- Can I suggest that we bring this together with data shapes and other datatype-describing-vocabulary under the denominator of 'application interoperability'?

2023-07-26 18:49 UTC, renoirb commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
I'm probably stating the obvious. It's probably out of scope, and I guess that's the point to ask here if this can/can't be part of this.

---

In any situation, an implementation of a pod (e.g. Inrupt‘s Community Solid Server "CSS", or another). will most probability also have a UI alongside the programmatic data centric HTTP API. In that API there's to say what to get, and some description of what's also possible and error messages and etc.

The human readable messages be probably in a language we can configure. Probably with locale, TimeZone, what text for an identifier, and etc.

Inrupt's CSS has ways to tell where the templates are (&lt;aside &gt;I haven't figured out how to actually do it, the examples in docs doesn't complete how to&lt;/aside&gt;) it's using a templating engine, etc. 

I'm wondering if we could have another HTTP API context root for the backend for the FrontEnd.

We could have a way to describe how to present the lists of things, and available actions stored into the pod. It's typically lists of objects, the properties (e.g. creation date, mime-type, etc.) for each of them, actions (e.g. delete, etc.) that are different based on the context of each of them (e.g. a directory with current user having right to write can upload a file vs a file you can write on would have a "replace" action).  

All that logic can quickly be deeply embedded into the UI layer and hard to separate and then limits people when making it their own.   We see that often in Microsoft SharePoint, we can't theme absolutely everything. — it's complex.

What if we had a way to describe collections of view descriptions. 

The descriptions could be for things like:

- **a list of items to display for one object**: (1) in a "date" component, use format "short", use property "CreatedAt" property for the value (the locale and calendar, and TimeZone be stored elsewhere, not here). (2) in a "file-type" component, use properties.

(I'll have to come back to continue writing this)

2023-07-26 19:04 UTC, elf-pavlik commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
The charter has a list of topics that are clearly in scope, as well as those which are out of scope. I think everything which isn't listed as *out of scope* is a good fit to be proposed using [New Work Item workflow](https://github.com/solid/specification/blob/main/CONTRIBUTING.md#new-work-item-proposal).
I don't see anything related to UI metadata listed as out of scope, which means that you should be able to simply propose your idea as a new work item.

2023-07-26 19:07 UTC, elf-pavlik commented on solid-cg-charter.md
> +In general, topics that are “out of scope” involve anything not directly related to the above. Some examples of these are listed here:
If we take the example of UI metadata [discussed above](https://github.com/solid/process/pull/323/files#r1270051384) can it be clearly qualified as **directly related** to some topics qualified as *in scope*?

2023-07-26 21:38 UTC, renoirb commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
Hi @elf-pavlik, trying to answer more directly to your points

> Your question concerns some agent (I suppose some application) which would use certain metadata (about a resource) that should be sufficient to render a UI display (of that resource) without relying on some proprietary library (i.e. other than a general library for interpreting that metadata). 

Put more simply: Solid Pod implementation may have more complex views than just "dressing up around" content.

Actions, things to do to them.

People might want to do more than change the "curtain".


> The question then is whether the CG scope includes looking into this metadata. Is this correct?
> 
> My questions to you would then be:
> 
> * Do you suppose this would require other metadata than that which describes what kind of resource we are talking about?

yes.

> * Can I suggest that we bring this together with data shapes and other datatype-describing-vocabulary under the denominator of 'application interoperability'?

I've noticed theres like tens of *Solid apps* to list files in a pod.  It's revealing, isn't it?

what if we have something that we could describe the actions that can be done, the messages, etc.  Without directly using $javaScriptFrameworkOfTheYear.  

Separate that metadata from the app.

2023-07-27 00:49 UTC, elf-pavlik commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
Hi @renoirb, I just wanted to clarify that @woutermont asked those specific questions.
I only suggested that what you describe doesn't seem *out of scope* and sounds like a great candidate for [New Work Item workflow](https://github.com/solid/specification/blob/main/CONTRIBUTING.md#new-work-item-proposal), which is referenced from the charter already. This would be a better way of clarifying the use cases and requirements, as well as comparing with other efforts like:
* https://www.hydra-cg.com/
* https://github.com/rdfjs/shacl-ui

and possibly other ones.

2023-07-27 04:19 UTC, renoirb commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
Thank you for clarifying.  I'm quick to jump to that type of description. Let's do that then.

2023-07-27 04:51 UTC, woutermont commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
@renoirb, thanks for providing more clarity!

> In any situation, an implementation of a pod [...] will most probability also have a UI alongside the programmatic data centric HTTP API. In that API there's to say what to get, and some description of what's also possible and error messages and etc. [...] I'm wondering if we could have another HTTP API context root [...] for the FrontEnd.

Okay, this is clear: is it within the scope of the CG to look into specifying some conformance constraints on the UI/Front-End of Solid storage providers? 

I'd say it is, but I would personally caution to do so specifically for storage frontends. I think the UI of a storage provider should be treated just like any other client application, and thus have no additional restrictions on how to render. But like @elf-pavlik said: _everything which isn't listed as out of scope is a good fit to be proposed [as a new Work Item]_. 

If you feel that this should be more present in the scopes mentioned in the charter, might I propose to change the first explicit scope to **Protocols for the storage, transmission<del> and</del><ins>,</ins> portability<ins> and display</ins> of data.**

> We could have a way to describe how to present the lists of things, and available actions stored into the pod. It's typically lists of objects, the properties [...] for each of them, actions [...] that are different based on the context of each of them [...] All that logic can quickly be deeply embedded into the UI layer and hard to separate and then limits people when making it their own. 

> What if we had a way to describe collections of view descriptions. [...] The description doesn't contain the objects themselves only a blueprint, not the info specific to the current user [...] [W]hat if we have something that we could describe the actions that can be done, the messages, etc. [...] Separate that metadata from the "app".

The way you describe it in the two excerpts above, though, feels much more in line with what is already being done on **interoperability** (e.g. [SAI](https://github.com/solid/data-interoperability-panel)). We look into application-independent (not storage-specific) ways to describe solid resources in such a way that all their type-level semantics can be known: this is metadata about **what kind of resource** a specific resource is (e.g. a Word document, live sensor data, a social media post according to some standard ...), including precisely what applications can count on to find in the resource (e.g. text encoded as Word98, the CreatedAt date of each sensor measurement, the list of foaf:Person who liked a post ...), and therefore this metadata also specifies exactly what an application can do with that resource (e.g. parse the text using a Word98 parser, display the date in one of the formats a CreatedAt date provides, find the foaf:name of those people ...), and how applications should write data to the resource.

Given a way to describe these semantics (e.g. ShaCL, ShEx, ShapeTrees), a storage server can then check incoming data, and guarantee all the above for outgoing data. Does what you describe correspond more or less to this?

2023-07-27 04:53 UTC, woutermont commented on solid-cg-charter.md
> +In general, topics that are “out of scope” involve anything not directly related to the above. Some examples of these are listed here:
[I believe so](https://github.com/solid/process/pull/323#discussion_r1275729604)

2023-07-27 04:57 UTC, woutermont commented on solid-cg-charter.md
> +* Access requests and grants.
Nitpicking, but this already falls under the second point "Authentication and authorization mechanisms."

2023-07-27 04:57 UTC, woutermont commented on solid-cg-charter.md
> +* Data shapes.
As mentioned during yesterdays CG call, I believe these two points would be better covered under a single broader point "Data interoperability".

2023-07-27 04:58 UTC, woutermont commented on solid-cg-charter.md
> +* Access requests and grants.
```suggestion
```

2023-07-27 04:59 UTC, woutermont commented on solid-cg-charter.md
> +* Data shapes.
```suggestion
* Data interoperability.
```

2023-07-27 06:19 UTC, SharonStrats approved these changes
Looks great!

2023-07-27 12:28 UTC, woutermont commented on solid-cg-charter.md
> +
Good clarification! That's how the W3C Process describes it anyway, but making this explicit can definitely help ease some worries.

2023-07-27 14:45 UTC, renoirb commented on solid-cg-charter.md
> +
Maybe it's already defined elsewhere. I just to be sure.

Is an affiliation implicit the day an employment change happen to a person, regardless whether the employer cares about their involvement?

2023-07-27 15:00 UTC, renoirb commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
> (...) I only suggested that what you describe doesn't seem _out of scope_ and sounds like a great candidate for [New Work Item workflow](https://github.com/solid/specification/blob/main/CONTRIBUTING.md#new-work-item-proposal), which is referenced from the charter already. This would be a better way of clarifying the use cases and requirements, (...)

OK. Glad to see my question about being *in or out of scope*, and what's next.

> (..) as well as comparing with other efforts like:
> 
> * https://www.hydra-cg.com/
> * https://github.com/rdfjs/shacl-ui
> 
> and possibly other ones.

OMG. I wasn't aware of Hydra (not *Captain Marvel's*)

I saw the mention in my 2019 research before my implementing of the idea back then.

http://launchany.com/resolving-the-frontendbackend-api-design-conflict/

I've looked at my notes, an article I referenced about the "conflict for Backend and FrontEnd API design" mentioning Hydra. It isn't new. I was just unaware and didn't follow that thread.

2023-07-27 15:15 UTC, renoirb commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
> Okay, this is clear: is it within the scope of the CG to look into specifying some conformance constraints on the UI/Front-End of Solid storage providers?


I agree that managing files be a separate application and we can use any we want.

Like X11 (windowing management) GTK separated from GNOME in Linux. (I haven't worked with the code, but as a SysAdmin, I've noticed that GTK is the toolkit to describe what's possible and GNOME is the user of it).


So, Solid manages files, some files can probably be read and served when the are in a format Solid can do something about.  Like appending at the end of a file, but maybe the contents as an object (I may have misunderstood this though).  Like a "contact" is stored into a file within the pod. A "contact" being an abstraction and managed as part of Solid. Other things like that may happen for other types of objects.

we may have more than one implementation popping up for managing contacts, like managing files.


But what if the implementation can only focus on their respective projects' scope "other logic" than the file management and managed object lifecycle.  

Like WebKit/Blink and Chromium. Then Brave has their own stuff added as value on top of Chromium.

> I'd say it is, but I would personally caution to do so specifically for storage frontends. I think the UI of a storage provider should be treated just like any other client application, and thus have no additional restrictions on how to render.

Yes. I agree.

What I'm talking about is not to tell *how* to render (aesthetics), but the state changed possibles and results of them. For the current user, locale, language, etc.

2023-07-27 15:34 UTC, woutermont commented on solid-cg-charter.md
> +
Good question 👍 

I guess we can use our official W3C listed affiliations for that? (When a person signs up for a W3C account in order to join a community, both on signup and when joining they have to agree to truthfully present their affiliations, and keep them updated.)

2023-07-27 15:50 UTC, woutermont commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
> But also, in case I wasn't clear, the **view description** [...] The how it looks isn't part of it.

Here I fundamentally disagree. What you are describing (headings, labels, selectors, making things editable ...) is all part of "how it looks" to me, or at least part of something that apps should be able to choose themselves, not be told how to do.

E.g. if I create an app/component to list contacts, without headings, with icons instead of labels, with no editable fields, with ugly long date formats ... then I should be allowed to do that. Solid is a data framework, not a style guide: such a guide is useful next to the spec, but a guide differs from a spec in that the former talks about suggested optimal choices, whilst the latter is about hard breaking conformance rules.

2023-07-27 16:15 UTC, csarven commented on solid-cg-charter.md
> +
Right that participants disclosing and updating their affiliations and any conflict of interests is part of W3C accounts and agreements.

2023-07-27 16:49 UTC, renoirb commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
So, if all of this is still relevant to Solid's use cases. I don't mind cleaning this up and put up elsewhere.

2023-07-27 19:15 UTC, renoirb commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
> Here I fundamentally disagree. What you are describing (...) is all part of "how it looks" to me, or at least part of something that apps should be able to choose themselves, not be told how to do.

I know, and agree too.

My proposal is about a way to describe processes, with what properties to plug in what *type of interactive element*. A "component" name here is to guide, not an actual one. 

It's the intention, to read (visualize) or change. Depending on the context. Because it's rarely only just about printing a string as-is.

Those "intentions" item can be a known list (for that process) of those things.  Then the thing that processes it would have to implement and register when it's time to display.

so the logic of gluing what to put where, etc. Is just about walking the list, using the hints from it, and do everything else.

> 
> E.g. if I create an app/component to list contacts, without headings, with icons instead of labels, with no editable fields, with ugly long date formats ... then I should be allowed to do that. Solid is a data framework, not a style guide: such a guide is useful next to the spec, but a guide differs from a spec in that the former talks about suggested optimal choices, whilst the latter is about hard breaking conformance rules.

2023-07-27 20:27 UTC, woutermont commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
As you describe it now, it feels much closer to Service Descriptions again. I would urge to look into those (they have some very basic but easy to grasp examples on the website of [RESTdesc](https://restdesc.org)). Since they can be extended with any RDF statements about some resource/service, the descriptions can be made very elaborate.

E.g. you could easily define 
  - that if you POST a resource with an `rdfs:label`, and an `rdfs:description` to `/things/`, they would be stored as an `owl:Thing`, and that the response would have it's URI in the `Location` header;
  - that if you POST anything else, the request will fail in a certain way;
  - that if you GET the URI of such an `owl:Thing`, e.g. `/things/0123`, with either `text/turtle` or `application/ld+json` as a `Content-Type` header, this would result in a response of the correct format, with the original data in the body, as well as a `dc:date` stating the date of creation, conforming to a specific date format;
  - that if you would perform a GET request on `/things/` itself, you would receive a body that instead holds only the `rdfs:label` of every `owl:Thing`, and the `dc:date` but possibly in another format; etc.

And that is just for reading and writing simple resources; all kinds of form interaction and side effects could also be described.

2023-07-27 20:30 UTC, woutermont commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
What I'm mostly trying to get at is that, if it's really not about display/style, but about the semantics of resources and actions on them, this is already clearly present in the scope as _data interoperability_; but that if this is not enough, we should maybe add something or leave you to propose something as a new work item. 🙂

2023-07-27 21:57 UTC, renoirb commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
I'll do some reading. Probably read more about RESTdesc, Hydra, etc. I'll write something somewhere to reorganize this, and see. 

I'll go through the new work process once I have more notes and see to use the mentioned technologies.

what if it's just me mapping what I'm trying to say, and what I've just been exposed to. Thanks.

In any case. W.r.t. scope and incubation. I might be able to make a PoC using the mechanics.

2023-07-27 22:00 UTC, renoirb commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
One thing though.  I make distinction between the data from a description of assembly of that data.

2023-07-28 06:49 UTC, csarven commented on solid-cg-charter.md
> +* Data shapes.
As per 2023-07-26 action: https://github.com/solid/specification/blob/main/meetings/2023-07-26.md#ui-layer-metadata

```suggestion
* Vocabularies and data shapes.
```

See also suggestion: https://github.com/solid/process/pull/323/files#r1275732235 and any resolution from thread: https://github.com/solid/process/pull/323/files#r1270051384

2023-07-28 09:02 UTC, csarven commented on solid-cg-charter.md
> +* Access requests and grants.
No objection. How do others think about this?

2023-07-28 09:05 UTC, csarven commented on solid-cg-charter.md
> +
Suggestion in response to thread https://github.com/solid/process/pull/323#discussion_r1270051384

```suggestion

* Application and UI affordances.

```

2023-07-28 09:07 UTC, csarven commented on solid-cg-charter.md
> +* Publishing test reports and communicating the level of adoption of technical reports.
The following Scope item covers a bit of the needs discussed here:

>Data models that can be used in storages, e.g., policies, data privacy and rights, provenance records and auditing, error messages.

(See also e.g., [structured error messages](https://github.com/solid/specification/issues/28), [service/storage description](https://github.com/solid/specification/issues/355) and use cases therein).

And we can add more to the listed examples there. Perhaps "actions"?

That aside, it'd be useful to revisit emphasis on class of work towards building smart(er) clients (Application, UI) in Solid that says a bit more than vocabs/data models/shapes/service descriptions/client-client. I'm in favour of a specific Scope item capturing "UI" or "Application". (Ditto what can capture for example the [UI ontology](http://www.w3.org/ns/ui)). I find the term "Interoperability" too broad - after all, all these efforts are towards interop. But, interop between what and what product as far as conformance is concerned? (see Solid QA work). [Variability in Specifications](https://www.w3.org/TR/spec-variability/) for instance generally mentions classes of products like Consumer/Player/Processor which may be closely related here.

I made an imperfect suggestion here https://github.com/solid/process/pull/323/files#r1277302683 , please review and suggestions towards what's intended if it is not adequate.

---

I suggest that we resolve this discussion soon. It is a touch too much into the weeds and perhaps we can use the solid/specification chat to continue the discussion and then propose changes here or make suggestions that can generally capture the related material.

2023-07-28 09:08 UTC, csarven commented on solid-cg-charter.md
> +In general, topics that are “out of scope” involve anything not directly related to the above. Some examples of these are listed here:
I generally agree but it may still be worthwhile to call out Application/UI as an item: https://github.com/solid/process/pull/323#discussion_r1277304951

2023-07-28 09:31 UTC, woutermont commented on solid-cg-charter.md
> +* Federation.
Just to make this somewhat more expressive
```suggestion
* Federation of trust between producers (storage, authentication, authorization ...).
```

2023-07-28 09:32 UTC, woutermont commented on solid-cg-charter.md
> +
To continue on your [comment](https://github.com/solid/process/pull/323#discussion_r1277304951) here: I feel that "Application affordances" is just as broad as "interoperability" 🤔

2023-07-28 09:40 UTC, woutermont commented on solid-cg-charter.md
> +* Vocabularies and data shapes.
Might I suggest the following:

```suggestion
* Metadata models that can be used in storages, e.g., policies, data privacy and rights, provenance records and auditing, error messages.
* Profile descriptions for social and software agents.
* Data Interoperability: sharing semantics of the content of resources (e.g. data shapes). 
* Service Interoperability: sharing semantics on the discovery of actions and access to resources (e.g. web service descriptions).
* User interface affordances: the display of data and services in a view.
* Vocabularies providing the necessary semantics for the mechanisms defined within the scope of this group.
```

2023-07-28 09:53 UTC, csarven commented on solid-cg-charter.md
> +* Federation.
I was thinking along the lines of generic message passing in a network (client->server->server*). It overlaps a bit with the work in Solid Notifications Protocol and ActivityPub - and better addressing interop across Solid and Fediverse (and open challenges within).

I think the trust aspect can be covered there as well but it is not limited to it. Similarly closely related is data cascading/flows: https://github.com/solid/specification/issues/151 .

I'm open to changing it to:

* Federation, e.g., message passing, trust, data cascading.

Or whatever minimal set of examples to clarify. Really don't want to boil the ocean here which is why I originally left it at Federation :)

2023-07-28 09:57 UTC, woutermont commented on solid-cg-charter.md
> +* Federation.
```suggestion
* Federation, e.g., message passing, trust, data cascading.
```

Sounds good to me 👍

2023-07-28 10:01 UTC, csarven commented on solid-cg-charter.md
> +* Vocabularies and data shapes.
That generally works for me. Let's hear it from the others.

Prefer "data" over "metadata" however.

Lowercase "interoperability".

Drop the brackets around "e.g."

Add "provisioning, portability" to examples under service interoperability.

2023-07-28 10:10 UTC, woutermont commented on solid-cg-charter.md
> +* Vocabularies and data shapes.
> Lowercase "interoperability".

Updated.

> Drop the brackets around "e.g."

Updated.

> Add "provisioning, portability" to examples under service interoperability.

Do you mean data portability? Should be under data interop rather. Or something else? (portability is broad, just like interop)

> Prefer "data" over "metadata" however.

For policy, provence, auditing etc. I think metadata works better. It is stuff we keep on top of and about the actual content. Calling models concerning those things 'metadata models' contrasts them with data interop, which are the actual data models.

2023-07-28 10:11 UTC, woutermont commented on solid-cg-charter.md
> +* Vocabularies and data shapes.
Alternatively, what about: _Models for metadata used by storages, e.g. ..._ ?

2023-07-28 13:47 UTC, elf-pavlik commented on solid-cg-charter.md
> +
TBH I still don't get the UI-specific affordances, if they are machine readable they can also be used as API.
Also when it comes to UI, are we talking about GUI and UIs accommodation for other accessibility needs?

2023-07-28 16:55 UTC, lecoqlibre commented
Thank you all for the work.

As I'm very new to this community and I don't have a great overview of everything my comment can't be as relevant as others. I also don't have any experience in W3C WG nor in charter writing.

That being said, I don't have any objection after reading the charter as there is nothing quite surprising comparing to what I see and understand of the current group. I find the "scope" gives a great list and is not limited and the "out of scope" makes sense. Concerning the amendments 5% seems few (= 13 person over 272) but it make sense if we consider the current active number of participants being between 10 and 20.

2023-07-28 19:28 UTC, renoirb commented
> @lecoqlibre:
> (...) I don't have any objection after reading the charter as there is nothing quite surprising comparing to what I see and understand of the current group. 
> (...) Concerning the amendments 5% seems few (= 13 person over 272) but it make sense if we consider the current active number of participants is between 10 and 20.

You bring a good point that made me raise a question.

What about the decision process and votes and this ratio?

I am in now a few CG, I might not be active in all of them for various reasons.

How is it in other CG? How do we track the votes, where? In WG it's in the meetings, there's a scribe, votes are based on (W3C's) members   and Invited experts.

There's probably something to tell about that elsewhere.

2023-07-31 22:38 UTC, renoirb commented on solid-cg-charter.md
> +
Thanks, then I guess it's just not a "blank check", just that it's in scope so we can talk about it and experiment.

2023-08-01 09:49 UTC, csarven commented on solid-cg-charter.md
> +* Vocabularies and data shapes.
Trying hard to avoid a data vs. metadata fight here :stuck_out_tongue_closed_eyes: 

Compared to "data", "metadata", often, but not always, has the connotation that it is hidden/grey information, and may not necessarily be in the view or accessible to the user, and so tends to be harder to update or maintain its accuracy. I was hoping that the charter emphasises on data because the notion generally includes metadata any way, and also to be in the frame of understanding that users (and their needs) come first. I ack that this stuff is a bit fuzzy.

https://www.rfc-editor.org/rfc/rfc3444 is one document (among many out there) that touches information/(meta)data model - doesn't mention metadata but some of the key areas that go under "data" seems to cover what can be viewed as metadata as well.

What do you think about going with:

"(Meta)data models.."

because I really want us to resolve this conversation and move on :)

2023-08-01 09:55 UTC, csarven commented on solid-cg-charter.md
> +* Access requests and grants.
Accepting suggestion based on rough consensus.

2023-08-01 09:56 UTC, csarven commented on solid-cg-charter.md
> +* Federation.
Accepting suggestion based on rough consensus.

2023-08-01 09:58 UTC, csarven commented on solid-cg-charter.md
> +
Accepting suggestion based on rough consensus.

2023-08-01 11:37 UTC, AbelVandenBriel approved these changes

2023-08-01 15:46 UTC, elf-pavlik commented
To address concerns of potential conflicts between Solid CG and Solid WG scopes.

The proposed Solid WG charter already states:
> The Working Group will not adopt new proposals until they have matured through the [W3C Solid Community Group](https://www.w3.org/groups/cg/solid) or another similar incubation phase.

https://solid.github.io/solid-wg-charter/charter/#add-new-deliverables

While Solid CG charter submitted in this PR states in *out of scope* section:

> Community Group's Work Items that have transitioned to a deliverable of an active Working Group.

https://github.com/solid/process/pull/323/files#diff-9c837fe839ded685179412e74e2cb90c107b8e51dedbca7024452b5f8c1de1ebR46

I think those two together set a clear boundary between CG and WG scopes. It also describes the pipeline where drafts get pre-processed in CG and can move into WG. I believe this is a common practice used in Credentials CG and possibly other ones.

2023-08-01 20:21 UTC, LabObjects approved these changes
The charter looks good (approve). Great work by all the contributors!

One small consideration would be a rewording part of the scope section opening sentence from 

"...enabling affordances for decentralised Web applications to create and use data across decentralised storages in a way that is secure and privacy respecting for individuals and communities."

 to:
"...enabling decentralised Web applications to create, use, and store data securely across disparate domains in a way that respects privacy for individuals and communities."

2023-08-02 00:10 UTC, csarven commented
Pavlik, there are threads discussing some of the chairing, starting with https://lists.w3.org/Archives/Public/public-solid/2018Oct/0004.html .

The CG self-organised to appoint chairs. There wasn't a process above and beyond folks stepping up to the service and the existing chairs appointed or stepped down overtime. It followed W3C's recommendations for CGs: https://www.w3.org/community/about/tool/#choose-chair .

I was appointed as co-chair in 2019 by Mitzi László, who was the chair at that time.

There was no ceremony about it around that time. I just served the community on the ground level, keeping stuff running and advancing, and as expected of the chair role.

I've gathered closest snapshots from the Internet Archive of the CG webpage indicating changes to chairs:

| Year | Archive | Chairs |
| - | - | - |
| 2018 | https://web.archive.org/web/20181003225240/https://www.w3.org/community/solid/ | Melvin Carvalho, Roy Leon |
| 2018 | https://web.archive.org/web/20181020172208/https://www.w3.org/community/solid/ | - |
| 2018 | https://web.archive.org/web/20181107170954/https://www.w3.org/community/solid/ | Phil J. Łaszkowicz, Brandon Whitehead |
| 2019 | https://web.archive.org/web/20190406022439/https://www.w3.org/community/solid/ | Phil J. Łaszkowicz, Brandon Whitehead, Mitzi László |
| 2019 | https://web.archive.org/web/20191228092722/https://www.w3.org/community/solid/ | Phil J. Łaszkowicz, Mitzi László, Sarven Capadisli |
| 2020 | https://web.archive.org/web/20201103121532/https://www.w3.org/community/solid/ | Phil J. Łaszkowicz, Sarven Capadisli |
| 2021 | https://web.archive.org/web/20210312202119/https://www.w3.org/community/solid/ | Sarven Capadisli |

If anyone would like to investigate further to help improve the charter, we or they can request data from W3C.

2023-08-02 00:58 UTC, CxRes approved these changes

2023-08-02 16:48 UTC, woutermont commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
Following up on [today's CG meeting](https://github.com/solid/specification/pull/550/files), I propose the following change to the license section, updating it to the rough consensus of the meeting (7/10 people explicitly in favour), and adding the discussed clause allowing an update pending the discussion on https://github.com/solid/process/issues/327.

```suggestion
The group will use the W3C Contributor License Agreement for all its draft specifications and other technical reports. For any other work item, including any software code artifacts, the group will use the MIT license. 

Derivations from the clause above can still be added to this charter, pending the discussion under [issue 327](https://github.com/solid/process/issues/327) of the [solid/process](https://github.com/solid/process) repository on GitHub, until at the latest the day before this charter goes into effect, viz. 2023-08-31. After the last amendment, or at the end of that day, this paragraph will be removed from the charter.
```

2023-08-02 17:09 UTC, elf-pavlik commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
LGTM, thank you @woutermont! To be extremely precise, let us mention both *W3C CLA & FSA*.

2023-08-02 18:33 UTC, elf-pavlik commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
Both are used by CG and BG, it is just a draft vs a final report.

[W3C Community Contributor License Agreement (CLA) Deed](https://www.w3.org/community/about/process/cla-deed/)
> Each Community and Business Group draft Specification includes this copyright statement:
>
> Copyright © [Date] the Contributors to the [Name/Version Information] Specification, published by the W3C [Name of Community/Business Group] under the [W3C Community Contributor License Agreement (CLA)](https://www.w3.org/community/about/agreements/cla/). A human-readable [summary](http://www.w3.org/community/about/agreements/cla-deed/) is available.

[W3C Community Final Specification Agreement (FSA) Deed](https://www.w3.org/community/about/process/fsa-deed/)
> Each Community and Business Group Final Specification includes this copyright statement:
>
> Copyright © [YEAR(S)] the Contributors to the [Name/Version Information] Specification, published by the W3C [Name of Community/Business Group] under the [W3C Community Final Specification Agreement (FSA)](http://www.w3.org/community/about/agreements/final/). A human-readable [summary](http://www.w3.org/community/about/agreements/fsa-deed/) is available.

2023-08-02 19:35 UTC, woutermont commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
Updated suggestion to include FSA.

2023-08-02 22:06 UTC, CxRes commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
Just checking if CG wants to use MIT or W3C Software License <https://www.w3.org/copyright/software-license-2023/> for code?

2023-08-02 23:34 UTC, elf-pavlik commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
Thanks @CxRes I mentioned it in #327 I think we should keep all the considerations there and here only focus on the wording and a clear reference to that dedicated issue.

2023-08-05 12:21 UTC, csarven commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
While this change suggestion is generally accurate with the agreement reached in the [2023-08-02 CG meeting](https://github.com/solid/specification/blob/main/meetings/2023-08-02.md#mit-license-andor-w3c-cla-and-fsa), I suggest updating with a bit more precision that's mentioned along the lines of https://github.com/solid/process/issues/327#issuecomment-1663770138 as well as general alignment that's intended by this charter with the W3C CG/BG Process.

2023-08-07 10:07 UTC, woutermont commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
Here is a suggestion that (literally) incorporates the latest update from https://github.com/solid/process/issues/327, including the proposal of @elf-pavlik and @CxRes to encourage MIT/OSI.

```suggestion
The group will use [W3C copyright licenses](https://www.w3.org/copyright/) for all its work items except any software code artifacts, for which the group will use the [MIT license](https://opensource.org/license/mit/). Concretely, this means that the group will use:

- the [W3C Contributor License Agreement](https://www.w3.org/community/about/process/cla/) (CLA) for all its draft specifications;
- the [W3C Final Specification Agreement](https://www.w3.org/community/about/process/final/) (FSA) for all its final specifications;
- the [W3C Document License](https://www.w3.org/copyright/document-license-2023/) for all its other public documents;
- a [dual license](https://www.w3.org/copyright/test-suites-licenses) combining the [W3C Test Suite License](https://www.w3.org/copyright/test-suite-license-2023/) with a [3-clause BSD license](https://www.w3.org/copyright/3-clause-bsd-license-2008/) for all its _authoritative_ test suites; and
- the [MIT license](https://opensource.org/license/mit/) for all its other software artifacts.

In particular, the group will NOT use the [W3C Software License](https://www.w3.org/copyright/software-license-2023/).

The group further strongly encourages its participants, as well as other stakeholders in the Solid ecosystem, to use the [MIT license](https://opensource.org/license/mit/), or another [OSI approved license](https://opensource.org/license/), for any open source software conforming to Solid specifications.

Derivations from the clauses in this section can still be added to this charter, pending the discussion under [issue 327](https://github.com/solid/process/issues/327) of the [solid/process](https://github.com/solid/process) repository on GitHub, until at the latest the day before this charter goes into effect, viz. 2023-08-31. After the last amendment, or at the end of that day, this paragraph will be removed from the charter.
```

2023-08-09 08:50 UTC, woutermont commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
Updated the latest suggestion to clearly distinguish between what the CG automatically has to adhere to (CLA, FSA), what work that ends up in a WG automatically has to adhere to (Document/Software/TestSuite Licenses), and what the CG freely chooses (MIT).

2023-08-09 08:51 UTC, woutermont commented on solid-cg-charter.md
> +The group will use the MIT license for all its work items.
For clarity, a rendered version.

---

The group will use [W3C copyright licenses](https://www.w3.org/copyright/) for all its work items except any software code artifacts, for which the group will use the [MIT license](https://opensource.org/license/mit/).

- Per W3C Process, all contributions to the group fall under the [W3C Community Contributor License Agreement](https://www.w3.org/community/about/process/cla/) (CLA). 

- When finalizing a W3C Community Group Draft Report towards a W3C Community Group Final Report, e.g., to transition the report to a Working Group, the group will contact all actual contributors to the report to secure their commitment to the [W3C Final Specification Agreement](https://www.w3.org/community/about/process/final/) (FSA). 

  Note that per W3C Process, all Technical Reports a Working Group publishes will fall under the [W3C Document License](https://www.w3.org/copyright/document-license-2023/).

- In accordance with the CLA, the group licenses all its software artifacts under the [MIT license](https://opensource.org/license/mit/). 
 
  Note that per W3C Process, all software artifacts that become part of a Working Group's Technical Reports will fall under the [W3C Software License](https://www.w3.org/copyright/software-license-2023/), and any W3C Authoritative Test Suite a Working Group publishes will fall under a [dual license](https://www.w3.org/copyright/test-suites-licenses/) combining the [W3C Test Suite License](https://www.w3.org/copyright/test-suite-license-2023/) and the [W3C's 3-clause BSD license](https://www.w3.org/copyright/3-clause-bsd-license-2008/).
 
The group strongly encourages its participants, as well as other stakeholders in the Solid ecosystem, to use the [MIT license](https://opensource.org/license/mit/), or another [OSI approved license](https://opensource.org/license/), for any open source software conforming to Solid specifications.

Derivations from the clauses in this section can still be added to this charter, pending the discussion under [issue 327](https://github.com/solid/process/issues/327) of the [solid/process](https://github.com/solid/process) repository on GitHub, until at the latest the day before this charter goes into effect, viz. 2023-08-31. After the last amendment, or at the end of that day, this paragraph will be removed from the charter.

2023-08-10 16:08 UTC, woutermont commented on solid-cg-charter.md
> +Derivations from the clauses in this section can still be added to this charter, pending the discussion under [issue 327](https://github.com/solid/process/issues/327) of the [solid/process](https://g
Argh 🙈 deviations of course. Thanks @TallTed !

2023-08-19 03:18 UTC, renoirb approved these changes
LGTM

2023-08-22 08:53 UTC, michielbdejong approved these changes

2023-08-22 15:38 UTC, renoirb commented
> A common procedure is just to use CG membership (literally people who have pressed 'Join this Group' button on the W3.org site) for votes.

That's to register participation interest. That'll add the participants email address and communication will be sent through it.

I've noticed the meeting invitation, there's the calendar link, etc. 

But the votes. Voting.  I'm assuming it's during a meeting, with Zakim, the minutes bot, tracking presences, ‘q+`,action items, topics, etc. like a normal WG?

2023-09-01 08:11 UTC, csarven commented on solid-cg-charter.md
> +* Vocabularies providing the necessary semantics for the mechanisms defined within the scope of this group.
Right, the current wording (based on https://github.com/solid/process/pull/323#pullrequestreview-1551681803 https://github.com/solid/process/pull/323#pullrequestreview-1551737297 ) is intended to cover what we had previously.

2023-09-01 14:38 UTC, woutermont approved these changes

2023-09-01 15:05 UTC, csarven commented on solid-cg-charter.md
> +  Note that per W3C Process, all Technical Reports a Working Group publishes will fall under the [W3C Document License](https://www.w3.org/copyright/document-license-2023/).
This note is not necessary.

```suggestion
```

2023-09-01 15:05 UTC, csarven commented on solid-cg-charter.md
> +  Note that per W3C Process, all software artifacts that become part of a Working Group's Technical Reports will fall under the [W3C Software License](https://www.w3.org/copyright/software-license-20
This note is not necessary.

```suggestion
```

2023-09-01 15:36 UTC, CxRes commented on solid-cg-charter.md
> +Deviations from the clauses in this section can still be added to this charter, pending the discussion under [issue 327](https://github.com/solid/process/issues/327) of the [solid/process](https://gi
Though it is a minor issue, I do not like the idea of putting in a specific clause in the charter itself, even if temporarily! Rigo has already responded, and we should clarify this next CG meeting. It is understood from the PR comments that this is the case.

IMHO, we are better served by the general amendment process to the CG charter (though this is kind of covered in the decision process).

2023-09-01 16:13 UTC, woutermont commented on solid-cg-charter.md
> +Deviations from the clauses in this section can still be added to this charter, pending the discussion under [issue 327](https://github.com/solid/process/issues/327) of the [solid/process](https://gi
@cxres, to be sure: we are not adding, but removing that clause from the charter, as was agreed we would do the 1st of September. It is indeed the standard amendment process that shall be used from now on, as was the consensus last meeting.

2023-09-01 16:37 UTC, CxRes commented on solid-cg-charter.md
> +Deviations from the clauses in this section can still be added to this charter, pending the discussion under [issue 327](https://github.com/solid/process/issues/327) of the [solid/process](https://gi
My bad!

2023-09-05 13:45 UTC, elf-pavlik commented on solid-cg-charter.md
> +  Note that per W3C Process, all Technical Reports a Working Group publishes will fall under the [W3C Document License](https://www.w3.org/copyright/document-license-2023/).
It will be better to make a separate small PR after our final meeting with Rigo, since we may see the need to add additional fine-tuning to the licensing section. Let's keep it all together in that PR.

2023-09-06 16:44 UTC, woutermont requested changes
As concluded in [today's meeting](https://github.com/solid/specification/pull/567).

2023-09-07 18:17 UTC, timbl approved these changes
Looks good to me with the no-notice bits in.

2023-09-07 18:34 UTC, csarven commented
Merging as per [2023-09-06 CG meeting decision](https://github.com/solid/specification/blob/main/meetings/2023-09-06.md#solid-cg-charter).

Thank you to everyone who contributed their time, knowledge, and passion to improve the charter through constructive discussions and collaboration.

We made it so! :)

2023-09-07 18:34 UTC, merged